#!/bin/bash
#
# ADARA "Fix IPTS" Script...! ;-D
#
# Script to Automate Changing the IPTS Proposal Number for Run(s)
# and Resubmitting Them Through the STS to Re-Catalog...! ;-D
#
# (Because it can happen that often... ;-)
#

#NOTIFY_EMAIL_LIST="parkerpg@ornl.gov rens@ornl.gov kohlja@ornl.gov"
NOTIFY_EMAIL_LIST="kohlja@ornl.gov"

MAILER="/usr/bin/Mail"

ADARA_PARSER="/usr/local/bin/adara-parser"

ADARA_CAT="/usr/local/bin/adaracat"

FINDNEXUS="/SNS/software/bin/findnexus"

NXDIFF="/SNS/software/bin/nxDiff"

SMS_CONFIG="/SNSlocal/sms/conf/smsd.conf"

SMS_DATA="/SNSlocal/sms/data"

XINETD_DIR="/etc/xinetd.d"

ARCHIVE_PATH="/"

STS1="sns-sts1.sns.gov"
STS2="sns-sts2.sns.gov"

TRUNCATE="/usr/bin/truncate"
Editor="/usr/bin/vim"
DIFF="/usr/bin/diff"
CMP="/usr/bin/cmp"
Less="/usr/bin/less"
AWK="/usr/bin/awk"
SSH="/usr/bin/ssh"
NC="/usr/bin/nc"
WC="/usr/bin/wc"
GREP="/bin/grep"
SED="/bin/sed"
CP="/bin/cp"
MV="/bin/mv"
LS="/bin/ls"

USAGE()
{
	echo -e "\nusage: adara_fix_ipts \\"
	echo "         [--inst=<INST>] [--facility=<SNS|HFIR>] \\"
	echo "         [--sts1|--sts2] [--sts|--sts_test|--sts_dummy] \\"
	echo "         [--sts_port=<STSPort>] \\"
	echo "         [--adara_parser=<${ADARA_PARSER}>] \\"
	echo "         [--sms_config=<${SMS_CONFIG}>] \\"
	echo "         [--sms_data=<${SMS_DATA}>] \\"
	echo "         [--archive_path=<${ARCHIVE_PATH}>] \\"
	echo "         [--run=<RunNumber1>] \\"
	echo "         [--run=<RunNumber2,RunNumber3,...>] \\"
	echo "         [--run=<RunNumber4-RunNumber5>] \\"
	echo "         [--ipts=<IPTS-nnnnn>] [--help]"
	echo
}

PARSE_RUN_NUMBERS()
{
	local _runlist="$1"

	# Strip Off Any Comma Separators...
	_runlist=`echo "${_runlist}" | ${SED} 's/,/ /g'`
	cksed=$?

	if [[ $cksed != 0 ]]; then
		echo -e "\nERROR Parsing Comma-Separated Run Number List...!"
		echo -e "\nBailing..."
		exit 111
	fi

	# Step Through Run Numbers Looking for Any Run Number Ranges
	local _runlistall
	local _run
	for _run in ${_runlist} ; do
		# Run Number Range
		if [[ "${_run}" =~ - ]]; then
			local _start
			local _end
			_start=`echo "${_run}" | ${AWK} -F "-" '{print $1}'`
			_end=`echo "${_run}" | ${AWK} -F "-" '{print $2}'`
			for (( i = _start ; i <= _end ; ++i )); do
				if [[ -z "${_runlistall}" ]]; then
					_runlistall="$i"
				else
					_runlistall="${_runlistall} $i"
				fi
			done
		# Plain Run Number
		else
			if [[ -z "${_runlistall}" ]]; then
				_runlistall="${_run}"
			else
				_runlistall="${_runlistall} ${_run}"
			fi
		fi
	done

	# Now Append Parsed Run Number List to Overall Run List
	if [[ -z "${RUN_NUMBERS}" ]]; then
		RUN_NUMBERS="${_runlistall}"
	else
		RUN_NUMBERS="${RUN_NUMBERS} ${_runlistall}"
	fi
	echo -e "\nAdding Run Number(s) ${_runlistall} to Run List."
}

CHECK_PROCEED()
{
	local _proceed_query="Proceed"
	local _alt_query=0

	if [[ "#$1#" != '##' ]]; then
		_proceed_query="$1"
		_alt_query=1
	fi

	local _proceed_ck=""

	echo -e -n "\n${_proceed_query} (yes/No)? "
	read _proceed_ck

	_proceed_ck=`echo "${_proceed_ck}" | tr '[:upper:]' '[:lower:]'`

	if [[ -z ${_proceed_ck} || ${_proceed_ck} == "n" \
			|| ${_proceed_ck} == "no" ]]; then
		# Alternate Query? Just Return...
		if [[ ${_alt_query} == 1 ]]; then
			return 99
		# Else Actually Exit Script...
		else
			echo -e "\nExiting ADARA Fix IPTS at User's Request.\n"
			exit 99
		fi
	fi

	return 0
}

#
# Parse Command Line Arguments
#

STS_HOST="${STS1}"

STS_SERVICE="sts_dummy"
STS_PORT=""

RUN_NUMBERS=""

IPTS_NEW=""

FACILITY=""

INST=""

for arg in "$@" ; do

	key=`echo "$arg" | ${AWK} -F = '{print $1}'`
	value=`echo "$arg" | ${AWK} -F = '{print $2}'`

	if [[ "#$key#" == '#--inst#' ]]; then
		INST="$value"
		echo -e "\nSetting Beamline Short Name to: ${INST}"
	elif [[ "#$key#" == '#--facility#' ]]; then
		FACILITY="$value"
		echo -e "\nSetting Facility Name to: ${FACILITY}"
	elif [[ "#$key#" == '#--sts1#' ]]; then
		STS_HOST="${STS1}"
		echo -e "\nSetting STS Host to: ${STS_HOST}"
	elif [[ "#$key#" == '#--sts2#' ]]; then
		STS_HOST="${STS2}"
		echo -e "\nSetting STS Host to: ${STS_HOST}"
	elif [[ "#$key#" == '#--sts#' ]]; then
		STS_SERVICE="sts"
		echo -e "\nSetting STS Service to: ${STS_SERVICE}"
	elif [[ "#$key#" == '#--sts_test#' ]]; then
		STS_SERVICE="sts_test"
		echo -e "\nSetting STS Service to: ${STS_SERVICE}"
	elif [[ "#$key#" == '#--sts_dummy#' ]]; then
		STS_SERVICE="sts_dummy"
		echo -e "\nSetting STS Service to: ${STS_SERVICE}"
	elif [[ "#$key#" == '#--sts_port#' ]]; then
		STS_PORT="$value"
		echo -e "\nSetting STS Port to: ${STS_PORT}"
	elif [[ "#$key#" == '#--adara_parser#' ]]; then
		ADARA_PARSER="${value}"
		echo -e "\nSetting ADARA Parser Path to:\n\t[${ADARA_PARSER}]"
	elif [[ "#$key#" == '#--sms_config#' ]]; then
		SMS_CONFIG="${value%/}"
		echo -e "\nSetting SMS Config Directory to:\n\t[${SMS_CONF}]"
	elif [[ "#$key#" == '#--sms_data#' ]]; then
		SMS_DATA="${value%/}"
		echo -e "\nSetting SMS Data Directory to:\n\t[${SMS_DATA}]"
	elif [[ "#$key#" == '#--archive_path#' ]]; then
		ARCHIVE_PATH="${value%/}"
		echo -e "\nSetting Archive Path Directory to:\n\t[${ARCHIVE_PATH}]"
	elif [[ "#$key#" == '#--run#' ]]; then
		PARSE_RUN_NUMBERS "${value}"
	elif [[ "#$key#" == '#--ipts#' ]]; then
		IPTS_NEW="${value}"
		if [[ ! "${IPTS_NEW}" =~ ^IPTS- ]]; then
			echo -e -n "\n*** WARNING: New Proposal \"${IPTS_NEW}\" "
			echo "Does Not Have the \"IPTS-\" Prefix!"
			CHECK_PROCEED
		fi
		echo -e "\nSetting New IPTS Proposal to: [${IPTS_NEW}]"
	elif [[ "#$key#" == '#--help#' || "#$key#" == '#-h#' ]]; then
		USAGE
		exit 0
	else
		echo -e "\nError: Unknown Command Line Option [${arg}]"
		USAGE
		exit 1
	fi

done

if [[ -z "${RUN_NUMBERS}" ]]; then
	echo -e "\nError: No Run Numbers Specified!"
	USAGE
	exit 2
fi

if [[ -z "${IPTS_NEW}" ]]; then
	echo -e "\nError: No Replacement IPTS Proposal Specified!"
	USAGE
	exit 3
fi

#
# Determine Proper STS Service Port...! ;-D
#

if [[ -z "${STS_PORT}" ]]; then

	echo -e "\nContacting STS Host \"${STS_HOST}\" via SSH"
	echo "to Determine Port for STS \"${STS_SERVICE}\" Service..."

	echo -e "\n${SSH} ${STS_HOST} ${GREP} port ${XINETD_DIR}/${STS_SERVICE}"

	# Set Bash Pipefail Option as Needed...
	pfck=`set -o | ${GREP} pipefail | ${AWK} '{print $2}'`
	if [[ "$pfck" == "off" ]]; then
		set -o pipefail
	fi

	STS_PORT=`${SSH} ${STS_HOST} \
		${GREP} "port" ${XINETD_DIR}/${STS_SERVICE} \
		| ${AWK} '{print $3}'`
	ckstsport=$?

	if [[ $ckstsport != 0 ]]; then
		echo -e -n "\nError Determining STS Port "
		echo "for \"${STS_SERVICE}\" Service on ${STS_HOST}...!"
		USAGE
		exit 4
	fi

	# Reset Bash Pipefail Option as Needed...
	if [[ "$pfck" == "off" ]]; then
		set +o pipefail
	fi

	echo -e "\nGot STS Port ${STS_PORT} for STS \"${STS_SERVICE}\" Service."
fi

#
# Ready to Begin...! :-D
#

echo -e "\n*** Updating IPTS for Run Numbers:\n\n\t[${RUN_NUMBERS}]\n"
echo "to New Proposal [${IPTS_NEW}]."

echo -e -n "\nUsing STS \"${STS_SERVICE}\" Service "
echo "on \"${STS_HOST}:${STS_PORT}\"."

CHECK_PROCEED

#
# Install and Check the Validity of a Modified Data File...
#
# usage: INSTALL_AND_CHECK_DATAFILE "${rundir}" "${datafile}"
#
# - Assumes New/Modified Data File Exists, of form "${datafile}.NEW-$$"...
# - Show File Differences to User...
# - Make Sure File Still ADARA-Parses...!
# - Copy Original Data File to Backup Copy Before Proceeding...
# - Install New Data File... (Overwrite Original...)
# - Re-Name the "proposal-*" Placeholder File in the Run Directory...!
# - Re-Submit SMS Raw Data Files to STS for Re-Translation...!
#
INSTALL_AND_CHECK_DATAFILE()
{
	# Run Directory
	if [[ "#$1#" == '##' ]]; then
		echo -e "\nError: No Run Directory Specified for Install Check!"
		echo -e "\nContinuing with Next Run Number..."
		return 11
	fi
	local _rundir="$1"
	shift

	# Data File
	if [[ "#$1#" == '##' ]]; then
		echo -e "\nError: No Data File Specified for Install Check!"
		echo -e "\nContinuing with Next Run Number..."
		return 12
	fi
	local _datafile="$1"
	shift

	# Show File Differences to User...

	echo -e "\nFile Differences After Proposal Id Substitution:\n"

	echo -e "<<< ${_datafile}"
	echo -e ">>> ${_datafile}.NEW-$$"

	${DIFF} --text \
		"${_rundir}/${_datafile}" \
		"${_rundir}/${_datafile}.NEW-$$"

	# Make Sure File Still ADARA-Parses...!

	echo -e "\nNow Verify Still a Valid Stream File with ADARA Parser..."
	echo -e -n "\n(Search for \"${IPTS_NEW%%[[:space:]]*}\" "
	echo "and Verify File Parses to End!)"

	CHECK_PROCEED

	${ADARA_PARSER} --showrun ${_rundir}/${_datafile}.NEW-$$ \
		| ${Less} "+/proposal_id"

	# Copy Original Data File to Backup Copy Before Proceeding...

	echo -e "\nBacking Up 1st ADARA Output Stream File for Run ${run}:"
	echo -e "\t[${_datafile}]"
	echo -e "\t->[${_datafile}.BACKUP-$$]"

	${CP} -i "${_rundir}/${_datafile}" "${_rundir}/${_datafile}.BACKUP-$$"
	ckcp=$?

	if [[ $ckcp != 0 ]]; then
		echo -e -n "\nERROR Copying Original Stream File for Backup "
		echo "of Run ${run}!"
		CHECK_PROCEED
		echo -e "\nContinuing with Next Run Number..."
		return 13
	fi

	# Install New Data File... (Overwrite Original Now...)

	echo -e "\nReady to Overwrite Original Data File with New One:"
	echo -e "\t[${_datafile}.NEW-$$]"
	echo -e "\t-> [${_datafile}]"

	CHECK_PROCEED

	echo -e "\nMoving Substituted Data File into Place of Original:"
	echo -e "\t[${_datafile}.NEW-$$]"
	echo -e "\t-> [${_datafile}]"

	${MV} "${_rundir}/${_datafile}.NEW-$$" "${_rundir}/${_datafile}"
	ckmvdata=$?

	if [[ $ckmvdata != 0 ]]; then
		echo -e -n "\nERROR Moving Modified Stream File Over Original "
		echo "for Run ${run}!"
		CHECK_PROCEED
		echo -e "\nContinuing with Next Run Number..."
		return 14
	fi

	#
	# Re-Name the "proposal-*" Placeholder File in the Run Directory...!
	#

	echo -e "\nRe-Naming Proposal Placeholder File in the Run Directory:"
	echo -e "\t[proposal-${ipts_old}]"
	echo -e "\t-> [proposal-${IPTS_NEW%%[[:space:]]*}]" # Strip Off Spaces

	${MV} -i \
		"${_rundir}/proposal-${ipts_old}" \
		"${_rundir}/proposal-${IPTS_NEW%%[[:space:]]*}" # Strip Off Spaces
	ckmvprop=$?

	if [[ $ckmvprop != 0 ]]; then
		echo -e -n "\nERROR Re-Naming Proposal Placeholder File "
		echo "for Run ${run}!"
		CHECK_PROCEED
		echo -e "\nContinuing..."
		# No Need to Give Up/Return Here, Just the Proposal Placeholder File
	fi

	#
	# Re-Submit SMS Raw Data Files to STS for Re-Translation...!
	#
	# Use "ADARACat" to Account for Any Intervening/Sent Paused Data...
	#

	echo -e -n "\nReady to Re-Submit SMS Raw Data Files "
	echo -e "for Run ${run} to STS for Re-Translation:"

	echo -e -n "\n\t-> Moving Run ${run} from Proposal \"${ipts_old}\" "
	echo -e "to \"${IPTS_NEW%%[[:space:]]*}\"..." # Strip Off Spaces

	echo -e -n "\nUsing STS \"${STS_SERVICE}\" Service "
	echo "on \"${STS_HOST}:${STS_PORT}\"."

	CHECK_PROCEED

	${ADARA_CAT} --run="${run}" --dir="${rundir}" \
		| ${NC} ${STS_HOST} ${STS_PORT}
	cksts=$?

	echo

	if [[ $cksts != 0 ]]; then
		echo -e -n "\nERROR Re-Submitting SMS Raw Data Files to STS "
		echo "for Run ${run}!"
		CHECK_PROCEED
		echo -e "\nContinuing with Next Run Number..."
		return 15
	fi

	#
	# Determine the Facility and Beamline (Short) Names
	# for Post-Processing Options...
	#

	# Set Bash Pipefail Option as Needed...
	pfck=`set -o | ${GREP} pipefail | ${AWK} '{print $2}'`
	if [[ "$pfck" == "off" ]]; then
		set -o pipefail
	fi

	# Only Retrieve the Facility Name if Not Explicitly Specified
	if [[ -z "${FACILITY}" ]]; then

		FACILITY=`${GREP} "facility" ${SMS_CONFIG} | ${GREP} -v ";" \
			| ${AWK} '{print $3}'`
		ckfac=$?

		if [[ $ckfac != 0 || -z ${FACILITY} ]]; then
			echo -e -n "\nERROR Determining Facility from SMS Config "
			echo "for Run ${run}!"
			echo -e "\n\t${SMS_CONFIG}"
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
			return 16
		fi

		echo -e "\nFacility Name Determined to be: [${FACILITY}]"

	fi

	# Only Retrieve the Beamline Short Name if Not Explicitly Specified
	if [[ -z "${INST}" ]]; then

		INST=`${GREP} "beamline_shortname" ${SMS_CONFIG} \
			| ${GREP} -v ";" | ${AWK} '{print $3}'`
		ckinst=$?

		if [[ $ckinst != 0 || -z ${INST} ]]; then
			echo -e -n "\nERROR Determining Beamline Short Name "
			echo "from SMS Config for Run ${run}!"
			echo -e "\n\t${SMS_CONFIG}"
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
			return 17
		fi

		echo -e "\nBeamline Short Name Determined to be: [${INST}]"

	fi

	# Reset Bash Pipefail Option as Needed...
	if [[ "$pfck" == "off" ]]; then
		set +o pipefail
	fi

	#
	# Now Verify the Differences Between the Original and New NeXus Files
	#

	# Prompt User for NeXus Diff Comparison...
	CHECK_PROCEED "Do You Want To Verify the Differences in the NeXus Files"
	local _ckdonxdiff=$?

	if [[ ${_ckdonxdiff} == 0 ]]; then

		# NeXus Diff the Original and New NeXus Files...

		local _archive="${ARCHIVE_PATH}"
		if [[ ${_archive:${#_archive} - 1} == "/" ]]; then
			_archive="${_archive}${FACILITY}/${INST}"
		else
			_archive="${_archive}/${FACILITY}/${INST}"
		fi

		local _nexus="nexus/${INST}_${run}.nxs.h5"

		echo -e "\n${NXDIFF} -L -S -l \\"
		echo -e "\t${_archive}/${IPTS_NEW%%[[:space:]]*}/${_nexus} \\"
		echo -e "\t${_archive}/${ipts_old}/${_nexus}"

		${NXDIFF} -L -S -l \
			"${_archive}/${IPTS_NEW%%[[:space:]]*}/${_nexus}" \
			"${_archive}/${ipts_old}/${_nexus}"
			# Strip Off Spaces ($IPTS_NEW)

	fi

	#
	# Now Check FindNeXus and the Catalog to Ensure the Run Moved...
	#

	# Prompt User for FindNeXus Catalog Check...
	CHECK_PROCEED "Do You Want To Use FindNeXus to Verify the Proposal Move"
	local _cknotify=$?

	if [[ ${_cknotify} == 0 ]]; then

		echo -e "\n${FINDNEXUS} -i ${INST} ${run}"
		echo

		${FINDNEXUS} -i ${INST} ${run}
		ckfindnexus=$?

		if [[ $ckfindnexus != 0 ]]; then
			echo -e -n "\nERROR Checking FindNeXus to Verify "
			echo "the Proposal Move for Run ${run}!"
			echo -e "\n\t${FINDNEXUS} -i ${INST} ${run}"
			CHECK_PROCEED
			echo -e "\nContinuing..."
			# No Need to Give Up/Return Here, Just FindNeXus Check...
		fi

	fi

	#
	# Now Send Email Notification of Re-Translation to Catalog Admins
	# (So They can Remove Any *Duplicate* Database Records...)
	#

	# Prompt User for Email Notification to Catalog Admins...
	CHECK_PROCEED "Do You Want To Notify the Catalog Admins of the Change"
	local _cknotify=$?

	if [[ ${_cknotify} == 0 ]]; then

		local _subject="[ADARA Fix IPTS]:"
		_subject="${_subject} ${FACILITY} ${INST} Run ${run}"
		_subject="${_subject} Moved from ${ipts_old}"
		_subject="${_subject} to ${IPTS_NEW%%[[:space:]]*}"
			# Strip Off Spaces

		echo -e "\n${MAILER} -s \\"
		echo -e "   \"${_subject}\" \\"
		echo -e "\t${NOTIFY_EMAIL_LIST}"

		${MAILER} -s "${_subject}" ${NOTIFY_EMAIL_LIST} <<NotifyEmailContent
This is an Automated Email Notification from the "ADARA Fix IPTS" script.

The ${FACILITY} ${INST} Run ${run} has been *Re-Translated*
to Move the Run from the Former Proposal:
		
	${ipts_old}

to the New Proposal:

	${IPTS_NEW%%[[:space:]]*}

Please Verify This Update to the ${FACILITY} Catalog Database,
and Remove Any Duplicate Records referring to the Old Proposal.

Thank You! :-D

   - ADARA Fix IPTS

NotifyEmailContent

		ckmail=$?

		if [[ $ckmail != 0 ]]; then
			echo -e -n "\nERROR Sending Email Notification "
			echo "to Catalog Admins for Run ${run}!"
			echo -e "\n\tTo: ${NOTIFY_EMAIL_LIST}"
			echo -e "\n\tSubject: ${_subject}"
			CHECK_PROCEED
			echo -e "\nContinuing..."
			# No Need to Give Up/Return Here, Just Catalog Admins Notify...
		fi

		echo -e "\nEmail Notification Sent to Catalog Admins:"
		echo -e "\n\t${NOTIFY_EMAIL_LIST}"

	fi

	#
	# Done with This Run...
	#

	echo -e "\nDone Modifying/Updating Run ${run}."

	return 0
}

#
# Manually Edit a Datafile, With Proper Cleanup/Newline Truncation...
#
# usage: MANUAL_EDIT "${rundir}" "${datafile}"
#
MANUAL_EDIT()
{
	# Run Directory
	if [[ "#$1#" == '##' ]]; then
		echo -e "\nError: No Run Directory Specified for Manual Editing!"
		echo -e "\nContinuing with Next Run Number..."
		return 20
	fi
	local _rundir="$1"
	shift

	# Data File
	if [[ "#$1#" == '##' ]]; then
		echo -e "\nError: No Data File Specified for Manual Editing!"
		echo -e "\nContinuing with Next Run Number..."
		return 21
	fi
	local _datafile="$1"
	shift

	# Prompt User for Manually Editing...
	CHECK_PROCEED "Do You Want To Manually Edit the Data File"
	local _ckmanedit=$?

	if [[ ${_ckmanedit} != 0 ]]; then
		return 22
	fi

	# Copy Original Data File to New Copy for Editing...

	echo -e "\nCopying 1st ADARA Output Stream File for Editing Run ${run}:"
	echo -e "\t[${_datafile}]"
	echo -e "\t->[${_datafile}.NEW-$$]"

	${CP} -i "${_rundir}/${_datafile}" "${_rundir}/${_datafile}.NEW-$$"
	ckcp=$?

	if [[ $ckcp != 0 ]]; then
		echo -e -n "\nERROR Copying Original Stream File to Edit "
		echo "for Run ${run}!"
		return 23
	fi

	# Pre-Edit Prompt...
	echo -e "\nReady to Manually Edit the Data File:"
	echo -e "\t[${_datafile}.NEW-$$]"
	echo -e "\tin [${_rundir}]"
	echo "to Change Proposal to ${IPTS_NEW}."
	CHECK_PROCEED "Proceed"
	if [[ $? != 0 ]]; then
		echo -e "\nOK, Skipping This Run Number."
		return 24
	fi

	# Manually Edit the Data File...
	${Editor} "+/proposal_id" "${_rundir}/${_datafile}.NEW-$$"
	ckedit=$?

	if [[ $ckedit != 0 ]]; then
		echo -e "\nERROR Manually Editing Data File for Run ${run}!"
		return 25
	fi

	# See If File Was Edited/Changed At All...

	${CMP} "${_rundir}/${_datafile}" "${_rundir}/${_datafile}.NEW-$$"
	ckcmp=$?

	if [[ $ckcmp == 0 ]]; then
		echo -e -n "\nNo Changes Made to Original Stream File "
		echo "for Run ${run}."
		return 26
	fi

	# Truncate the Extra Newline that Gets Added When Manually Editing!

	echo -e "\nTruncating Trailing Newline from Edited File:"
	echo -e "\t[${_datafile}.NEW-$$]"

	${TRUNCATE} --size=-1 "${_rundir}/${_datafile}.NEW-$$"
	cktrunc=$?

	if [[ $cktrunc != 0 ]]; then
		echo -e -n "\nERROR Truncating Newline from "
		echo -e "Manually Edited Data File for Run ${run}!"
		return 27
	fi

	# Install and Check Modified Data File...
	INSTALL_AND_CHECK_DATAFILE "${_rundir}" "${_datafile}"
	ckinstall=$?

	if [[ $ckinstall != 0 ]]; then
		echo -e -n "\nERROR Installing and Checking "
		echo -e "Manually Edited Data File for Run ${run}!"
		return ${ckinstall}
	fi

	# Manual Edit Successful!
	return 0
}

#
# Process Each Run Number in Turn...
#

for run in ${RUN_NUMBERS} ; do

	echo -e "\nProcessing Run Number: ${run}"

	#
	# Find the SMS Raw Data Files for This Run...! ;-D
	#

	rundir=`${LS} -d ${SMS_DATA}/*/*-run-${run} 2>&1`
	ckrundir=$?

	if [[ $ckrundir != 0 ]]; then
		echo -e "\nERROR Locating SMS Raw Data Directory for Run ${run}!"
		CHECK_PROCEED
		echo -e "\nContinuing with Next Run Number..."
		continue
	fi

	echo -e "\nFound SMS Raw Data Directory for Run ${run}:\n\t[${rundir}]"

	#
	# Locate & Backup the First ADARA Output Stream File for This Run
	#

	datafile=`${LS} "${rundir}" | ${GREP} -E "^f0+1-run-${run}.adara$"`
	ckdatafile=$?

	if [[ $ckdatafile != 0 ]]; then
		echo -e -n "\nERROR Locating 1st ADARA Output Stream File "
		echo "for Run ${run}!"
		CHECK_PROCEED
		echo -e "\nContinuing with Next Run Number..."
		continue
	fi

	# Make Sure We Only Got *1* Data File...! ;-D
	ckone=`echo "${datafile}" | ${WC} | ${AWK} '{print $1}'`

	if [[ ${ckone} != 1 ]]; then
		echo -e -n "\nERROR: Multiple Output Stream Files Found "
		echo -e "for Run ${run}!\n"
		echo -e "${datafile}\n"
		CHECK_PROCEED
		echo -e "\nContinuing with Next Run Number..."
		continue
	fi

	echo -e "\nFound 1st ADARA Output Stream File for Run ${run}:"
	echo -e "\t[${datafile}]"

	#
	# Determine What the Current IPTS Proposal is for This Run...
	#
	# - Fortunately, the IPTS Proposal is Stored in the RunInfo Packet
	# as Plain Text XML, So We Can Parse and Substitute It "Easily"... ;-D
	#
	# Note: Be Careful to _Avoid_ Things like "IPTS-ITEMS" in the RunInfo!
	# - Better Use the XML Tag "<proposal_id>" instead of plain "IPTS"...
	# - This covers the case where the Original Proposal was _Not_ "IPTS-*".
	#

	ipts_old_line=`${GREP} --text "<proposal_id>" "${rundir}/${datafile}"`
	ckoldiptsline=$?

	if [[ $ckoldiptsline != 0 ]]; then
		echo -e -n "\nERROR Extracting Old Proposal Line from Stream File "
		echo -e "for Run ${run}!\n"
		echo -e "\t[${ipts_old_line}]"
		MANUAL_EDIT "${rundir}" "${datafile}"
		if [[ $? != 0 ]]; then
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
		fi
		continue
	fi

	# Make Sure We Only Got *1* Old Proposal Id Line...! ;-D
	ckoneline=`echo "${ipts_old_line}" | ${WC} | ${AWK} '{print $1}'`

	if [[ ${ckoneline} != 1 ]]; then
		echo -e -n "\nERROR: Multiple Proposal Id Lines Found "
		echo -e "for Run ${run}!\n"
		echo -e "${ipts_old_line}\n"
		MANUAL_EDIT "${rundir}" "${datafile}"
		if [[ $? != 0 ]]; then
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
		fi
		continue
	fi

	echo -e "\nFound Old Proposal Id Line for Run ${run}:"
	echo -e "\t[${ipts_old_line}]"

	ipts_old=`echo "${ipts_old_line}" | ${AWK} -F "[<>]" '{print $3}'`
	ckoldipts=$?

	if [[ $ckoldipts != 0 ]]; then
		echo -e -n "\nERROR Extracting Old Proposal from Stream File "
		echo "for Run ${run}!"
		MANUAL_EDIT "${rundir}" "${datafile}"
		if [[ $? != 0 ]]; then
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
		fi
		continue
	fi

	echo -e "\nFound Old Proposal Id for Run ${run}: [${ipts_old}]"

	#
	# Compare the *Length* of the Old and New Proposal Ids,
	# to Carefully Determine How We Handle the Substitution
	# Without _Changing the Size_ of the XML Payload in the
	# ADARA RunInfo Packet...! ;-D
	#

	# Starting Point for New Proposal Id Substitution Line...
	ipts_new_line="${ipts_old_line}"

	# New IPTS is _Shorter_ than Old IPTS, Just Pad with White Space...
	if [[ ${#IPTS_NEW} -lt ${#ipts_old} ]]; then

		len_diff=$(( ${#ipts_old} - ${#IPTS_NEW} ))

		echo -e -n "\nNew Proposal Id [${IPTS_NEW}] is "
		echo "_Shorter_ than Old [${ipts_old}]:"
		echo -e -n "\t${#ipts_old} - ${#IPTS_NEW} = ${len_diff} "
		echo "Spaces to Pad."

		for (( i = 0 ; i < ${len_diff} ; ++i )); do
			IPTS_NEW="${IPTS_NEW} "
		done

		echo -e "\nResulting New Proposal Id is: [${IPTS_NEW}]"
	
	# New IPTS is _Longer_ than Old IPTS, Just Pad with White Space...
	elif [[ ${#IPTS_NEW} -gt ${#ipts_old} ]]; then

		len_diff=$(( ${#IPTS_NEW} - ${#ipts_old} ))

		echo -e -n "\nNew Proposal Id [${IPTS_NEW}] is "
		echo "_Longer_ than Old [${ipts_old}]:"
		echo -e -n "\t${#IPTS_NEW} - ${#ipts_old} = ${len_diff} "
		echo "Spaces to Remove from Line!"

		# Try to Remove Sufficient Spaces from Old Proposal Id Line...!

		skip_run=0

		for (( i = 0 ; i < ${len_diff} ; ++i )); do

			ckspc=`echo "${ipts_new_line}" | ${GREP} -c " "`
			if [[ "$ckspc" != "1" ]]; then
				echo -e -n "\nERROR: Insufficient White Space to Remove "
				echo "in Old Proposal Id Line!"
				MANUAL_EDIT "${rundir}" "${datafile}"
				if [[ $? != 0 ]]; then
					CHECK_PROCEED
					echo -e "\nContinuing with Next Run Number..."
				fi
				skip_run=1
				break
			fi

			# Take Any Space We Can Get...! ;-D
			ipts_new_line=`echo "${ipts_new_line}" | ${SED} 's/ //'`
			cksedspc=$?

			if [[ $cksedspc != 0 ]]; then
				echo -e "\nERROR Stripping White Space from IPTS Line...!"
				MANUAL_EDIT "${rundir}" "${datafile}"
				if [[ $? != 0 ]]; then
					CHECK_PROCEED
					echo -e "\nContinuing with Next Run Number..."
				fi
				skip_run=1
				break
			fi

		done

		# Skip This Run, We Had a Failure...
		if [[ $skip_run == 1 ]]; then
			continue
		fi

		echo -e "\nResulting New/Old Proposal Id Line Template is:"
		echo -e "\t[${ipts_new_line}]"

	else

		echo -e -n "\nNew Proposal Id [${IPTS_NEW}] is "
		echo "_Same_ Length as Old [${ipts_old}]:"
		echo -e "\t${#IPTS_NEW} = ${#ipts_old}"

	fi

	#
	# Now Substitute Old IPTS for New IPTS in New Proposal Id Line...
	#

	ipts_new_line=`echo "${ipts_new_line}" \
		| ${SED} "s/${ipts_old}/${IPTS_NEW}/"`
	cksedprop=$?

	if [[ $cksedprop != 0 ]]; then
		echo -e "\nERROR Substituting Proposal Ids in IPTS Line...!"
		MANUAL_EDIT "${rundir}" "${datafile}"
		if [[ $? != 0 ]]; then
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
		fi
		continue
	fi

	echo -e "\nFinal Proposal Id Line Substitution:"
	echo -e "\told: [${ipts_old_line}]"
	echo -e "\tnew: [${ipts_new_line}]"

	CHECK_PROCEED

	#
	# Actually Make the Data File Substitution...! ;-D
	#

	# Substitute from Original Data File into New Version... :-D

	echo -e -n "\nSubstituting New Proposal Id [${IPTS_NEW}] "
	echo "into New Data File:"
	echo -e "\t[${datafile}]"
	echo -e "\t-> ${datafile}.NEW-$$"

	${SED} "s@${ipts_old_line}@${ipts_new_line}@" \
		"${rundir}/${datafile}" > "${rundir}/${datafile}.NEW-$$"
	ckseddata=$?

	if [[ $ckseddata != 0 ]]; then
		echo -e "\nERROR Substituting New Proposal Id into Data File...!"
		MANUAL_EDIT "${rundir}" "${datafile}"
		if [[ $? != 0 ]]; then
			CHECK_PROCEED
			echo -e "\nContinuing with Next Run Number..."
		fi
		continue
	fi

	# Install and Check Modified Data File...
	INSTALL_AND_CHECK_DATAFILE "${rundir}" "${datafile}"

done

#
# Done
#

echo -e "\nDone.\n"

