#!/bin/bash
#
# ADARA Retranslate "Manual Processing Needed" Runs at a Beamline...
#
# (as so often happens hysterically, with old leftover runs that didn't
# complete or properly translate in the past... ;-D)
#

#
# Defaults:
#

ADARA_ADD_RUN_END="/usr/local/bin/adara_add_run_end"

ADARA_PARSER="/usr/local/bin/adara-parser"

DEFAULT_STC_HOST="stc1.ornl.gov"

XINETD_DIR="/etc/xinetd.d"

STC_PORT_HFIR="31420"
STC_PORT_SNS="31417"

SMS_DATA="/SNSlocal/sms/data"

SMS_LOG="/var/log/smsd.log"

BASENAME="/usr/bin/basename"
DIRNAME="/usr/bin/dirname"
HEAD="/usr/bin/head"
TAIL="/usr/bin/tail"
AWK="/usr/bin/awk"
SSH="/usr/bin/ssh"
GREP="/bin/grep"
LS="/bin/ls"

USAGE()
{
	echo -e "\nusage: adara_retranslate_manual \\"
	echo "    [--inst=<INST>] [--facility=<SNS|HFIR>] \\"
	echo "    [--stc1|--stc2|--stc_host=<STC_HOST>] \\"
	echo "    [--stc|--stc_test|--stc_dummy|--stc_hfir|--stc_hfir_test] \\"
	echo "    [--stc_port=<STCPort>] \\"
	echo "    [--adara_add_run_end=<${ADARA_ADD_RUN_END}>] \\"
	echo "    [--adara_parser=<${ADARA_PARSER}>] \\"
	echo "    [--alt=\"-mon\"] \\"
	echo "    [--sms_data=<${SMS_DATA}>] \\"
	echo "    [--sms_log=<${SMS_LOG}>] \\"
	echo "    [--help|-h]"
	echo
}

CHECK_PROCEED()
{
	local _proceed_query="Proceed"

	if [[ "#$1#" != '##' ]]; then
		_proceed_query="$1"
	fi

	local _proceed_ck=""

	echo -e -n "\n${_proceed_query} (yes/No)? "
	read _proceed_ck

	_proceed_ck=`echo "${_proceed_ck}" | tr '[:upper:]' '[:lower:]'`

	if [[ -z ${_proceed_ck} || ${_proceed_ck} == "n" \
			|| ${_proceed_ck} == "no" ]]; then
		return 1
	fi

	return 0
}

# Parse Command Line Options...

FACILITY=""
INST=""
ALT=""

STC_SERVICE=""
STC_HOST=""

STC_PORT=""

for arg in "$@" ; do

	key=`echo "$arg" | ${AWK} -F = '{print $1}'`
	value=`echo "$arg" | ${AWK} -F = '{print $2}'`

	if [[ "#$key#" == '#--inst#' ]]; then
		INST="$value"
		echo -e "\nSetting Beamline Short Name to: ${INST}"
	elif [[ "#$key#" == '#--facility#' ]]; then
		FACILITY="$value"
		echo -e "\nSetting Facility Name to: ${FACILITY}"
		if [[ ${FACILITY} == "SNS" ]]; then
			STC_PORT="${STC_PORT_SNS}"
			echo -e "\nSetting STC Port to: ${STC_PORT}"
		elif [[ ${FACILITY} == "HFIR" ]]; then
			STC_PORT="${STC_PORT_HFIR}"
			echo -e "\nSetting STC Port to: ${STC_PORT}"
		else
			echo -e "\nERROR: Unknown Facility Keyword \"${FACILITY}\"...!"
			echo -e "\nCannot Deduce STC Port...!"
		fi
	elif [[ "#$key#" == '#--stc1#' || "#$key#" == '#--stc2#' ]]; then
		STC_HOST="${key}"
		echo -e "\nSetting STC Host to: ${STC_HOST}"
	elif [[ "#$key#" == '#--stc_host#' ]]; then
		STC_HOST="${key}=${value}"
		echo -e "\nSetting STC Host to: ${STC_HOST}"
	elif [[ "#$key#" == '#--stc#' || "#$key#" == '#--stc_test#'
			|| "#$key#" == '#--stc_dummy#'
			|| "#$key#" == '#--stc_hfir#'
			|| "#$key#" == '#--stc_hfir_test#' ]]; then
		STC_SERVICE="${key}"
		echo -e "\nSetting STC Service to: ${STC_SERVICE}"
		echo -e "\nContacting STC Host \"${DEFAULT_STC_HOST}\" via SSH"
		echo "to Determine Port for STC \"${STC_SERVICE}\" Service..."
		echo -e -n "\n${SSH} ${DEFAULT_STC_HOST}"
		echo -e " ${GREP} port ${XINETD_DIR}/${STC_SERVICE}"
		STC_PORT=`${SSH} ${DEFAULT_STC_HOST} \
			${GREP} "port" ${XINETD_DIR}/${STC_SERVICE} \
			| ${AWK} '{print $3}'`
		echo -e \
			"\nGot STC Port ${STC_PORT} for STC \"${STC_SERVICE}\" Service."
	elif [[ "#$key#" == '#--stc_port#' ]]; then
		STC_PORT="$value"
		echo -e "\nSetting STC Port to: ${STC_PORT}"
	elif [[ "#$key#" == '#--adara_add_run_end#' ]]; then
		ADARA_ADD_RUN_END="${value}"
		echo -e "\nSetting ADARA Add Run End Path to:"
		echo -e "\t[${ADARA_ADD_RUN_END}]"
	elif [[ "#$key#" == '#--adara_parser#' ]]; then
		ADARA_PARSER="${value}"
		echo -e "\nSetting ADARA Parser Path to:\n\t[${ADARA_PARSER}]"
	elif [[ "#$key#" == '#--alt#' ]]; then
		ALT="$value"
		echo -e "\nSetting Alternate SMS Suffix to: [$ALT]"
		SMS_DATA="/SNSlocal/sms${ALT}/data"
		echo -e "\nSetting SMS Data Directory to:\n\t[${SMS_DATA}]"
		SMS_LOG="/var/log/smsd${ALT}.log"
		echo -e "\nSetting SMS Log File to:\n\t[${SMS_LOG}]"
	elif [[ "#$key#" == '#--sms_data#' ]]; then
		SMS_DATA="${value%/}"
		echo -e "\nSetting SMS Data Directory to:\n\t[${SMS_DATA}]"
	elif [[ "#$key#" == '#--sms_log#' ]]; then
		SMS_LOG="${value}"
		echo -e "\nSetting SMS Log File to:\n\t[${SMS_LOG}]"
	elif [[ "#$key#" == '#--help#' || "#$key#" == '#-h#' ]]; then
		USAGE
		exit 0
	else
		echo -e "\nERROR: Unknown Command Line Option [${arg}]"
		USAGE
		exit 1
	fi

done

if [[ -z "${INST}" ]]; then
	echo -e "\nERROR: No Beamline Short Name Specified!"
	USAGE
	exit 2
fi

# Check for "Manual Processing Required" Token Files...

MANS=`${LS} ${SMS_DATA}/2*/*run*/man*`

for man in ${MANS} ; do

	echo -e "\n$man"

	dir=`${DIRNAME} ${man}`

	echo -e "\ndir=[$dir]"

	echo
	${LS} -lt $dir | ${HEAD}

	run=`${BASENAME} $dir | ${AWK} -F "-" '{print $4}'`

	echo -e "\nrun=[$run]"

	echo
	file=`${LS} -r ${dir}/m*.adara ${dir}/f*.adara | ${HEAD} -1`

	basefile=`${BASENAME} ${file}`

	echo -e "\nfile=[$basefile]"

	CHECK_PROCEED "Continue"

	if [[ $? == 0 ]]; then

		${ADARA_PARSER} $file | ${TAIL}

		CHECK_PROCEED "Continue with ADARA Add Run End..."

		if [[ $? == 0 ]]; then

			${ADARA_ADD_RUN_END} --inst=$INST --facility=${FACILITY} \
				${STC_HOST} ${STC_SERVICE} \
				--stc_port=${STC_PORT} --run=${run}

			${LS} -lt ${dir} | ${HEAD}

		else

			CHECK_PROCEED "Continue with SMS Rescan Run Dir..."

			if [[ $? == 0 ]]; then

				pushd $dir

				/bin/rm manual_processing_needed

				caput -S ${BL}:SMS:StorageManager:RescanRunDir `pwd`

				sleep 3

				grep "${run}" ${SMS_LOG} | ${TAIL}

				echo

				${LS} -lt | ${HEAD}

				CHECK_PROCEED "Continue"

				popd

			fi

		fi

	fi

done

