#!/bin/bash

# default settings
SMSD_CONFIG="/SNSlocal/sms/conf/smsd.conf"
REPO_CONFIG="./sms/conf/smsd.conf"
CONFIG_REPO="/home/controls/config"
CONFIG_USER="snsdata"
TMP_DIR="/tmp"
WAIT="-w 9"

#
# Option Configurations
#

# Option Types/Indexing...

declare -A is_indexed
declare -A idName

is_indexed["sms"]=0
idName["sms"]="SMS"

is_indexed["runinfo"]=0
idName["runinfo"]="RunInfo"

is_indexed["marker"]=0
idName["marker"]="Marker"

is_indexed["source"]=1
idName["source"]="Source"

is_indexed["ctrl"]=0
idName["ctrl"]="Control"

is_indexed["storage"]=0
idName["storage"]="Storage"

is_indexed["sts"]=0
idName["sts"]="STS"


# Options...

num_options=0

option_id_type[$num_options]="source"
option_name[$num_options]="enabled"
option_pv[$num_options]="SMS:DataSource:XXX_INDEX_XXX:Enabled"
option_value_type[$num_options]="BOOL_VALUE(Enabled/Disabled)"
option_label[$num_options]="[Enable/Disabled Data Source]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="source"
option_name[$num_options]="connect_retry"
option_pv[$num_options]="SMS:DataSource:XXX_INDEX_XXX:ConnectRetry"
option_value_type[$num_options]="FLOAT64_VALUE(seconds)"
option_label[$num_options]="[Data Source Disconnect Retry Timeout]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="source"
option_name[$num_options]="connect_timeout"
option_pv[$num_options]="SMS:DataSource:XXX_INDEX_XXX:ConnectTimeout"
option_value_type[$num_options]="FLOAT64_VALUE(seconds)"
option_label[$num_options]="[Data Source Connection Timeout]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="source"
option_name[$num_options]="data_timeout"
option_pv[$num_options]="SMS:DataSource:XXX_INDEX_XXX:DataTimeout"
option_value_type[$num_options]="FLOAT64_VALUE(seconds)"
option_label[$num_options]="[Data Source Data Delivery Timeout]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="source"
option_name[$num_options]="ignore_eop"
option_pv[$num_options]="SMS:DataSource:XXX_INDEX_XXX:IgnoreEoP"
option_value_type[$num_options]="BOOL_VALUE(true/false)"
option_label[$num_options]="[Ignore End-of-Pulse]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="ctrl"
option_name[$num_options]="no_eop_pulse_buffer_size"
option_pv[$num_options]="SMS:Control:NoEoPPulseBufferSize"
option_value_type[$num_options]="UINT32_VALUE(pulses)"
option_label[$num_options]="[No EoP Pulse Buffer Size]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="storage"
option_name[$num_options]="poolsize"
option_pv[$num_options]="SMS:StorageManager:Poolsize"
option_value_type[$num_options]="UINT32_VALUE+[G|M]"
option_label[$num_options]="[Storage Poolsize (Max Blocks Allowed)]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="storage"
option_name[$num_options]="percent"
option_pv[$num_options]="SMS:StorageManager:Percent"
option_value_type[$num_options]="UINT32_VALUE(percent)"
option_label[$num_options]="[Percent of Storage (Max Blocks Allowed)]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="storage"
option_name[$num_options]="max_blocks_allowed"
option_pv[$num_options]="SMS:StorageManager:MaxBlocksAllowed"
option_value_type[$num_options]="UINT32_VALUE(blocks)"
option_label[$num_options]="[Max Blocks of Storage Allowed]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="sts"
option_name[$num_options]="connect_timeout"
option_pv[$num_options]="SMS:STSClient:ConnectTimeout"
option_value_type[$num_options]="FLOAT64_VALUE(seconds)"
option_label[$num_options]="[STS Client Connection Timeout]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="sts"
option_name[$num_options]="reconnect_timeout"
option_pv[$num_options]="SMS:STSClient:ReconnectTimeout"
option_value_type[$num_options]="FLOAT64_VALUE(seconds)"
option_label[$num_options]="[STS Client Re-Connection Timeout]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="sts"
option_name[$num_options]="transient_timeout"
option_pv[$num_options]="SMS:STSClient:TransientTimeout"
option_value_type[$num_options]="FLOAT64_VALUE(seconds)"
option_label[$num_options]="[STS Client Transient Error Retry Timeout]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="sts"
option_name[$num_options]="max_connections"
option_pv[$num_options]="SMS:STSClient:MaxConnections"
option_value_type[$num_options]="UINT32_VALUE(connections)"
option_label[$num_options]="[Max Simultaneous STS Client Connections]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="sts"
option_name[$num_options]="max_requeue_count"
option_pv[$num_options]="SMS:STSClient:MaxRequeueCount"
option_value_type[$num_options]="UINT32_VALUE(requeues)"
option_label[$num_options]="[Max STS Client Error Re-Queue Attempts]"
num_options=$(( num_options + 1 ))

option_id_type[$num_options]="sts"
option_name[$num_options]="service_uri"
option_pv[$num_options]="SMS:STSClient:ServiceURI"
option_value_type[$num_options]="IP_ADDR:IP_PORT(service)"
option_label[$num_options]="[STS Client Service URI]"
num_options=$(( num_options + 1 ))

#
# Dump Usage
#

USAGE()
{
	echo
	echo "usage:  liveconf \\"
	echo "            [--beamline=BL14B] [--config=./smsd.conf] \\"
	echo "            [--repo=/home/controls/config] \\"
	echo "            [--option=\"id:name<value>\"] \\"
	echo "            [status] [run_status] [data_status] [sys_status] \\"
	echo "            [--testonly] [--help]"
	echo

	echo "Available Options:"
	echo

	for i in $( seq 0 $(( num_options - 1 )) ) ; do
		echo -n "   --option=\"${option_id_type[$i]}"
		if [ ${is_indexed[${option_id_type[$i]}]} == 1 ]; then
			echo -n "<N>"
		fi
		echo ":${option_name[$i]}<${option_value_type[$i]}>\""
		echo "      ${option_label[$i]}"
	done

	echo
}

# Check for any of possible required command line options (else 'usage')
if [ $# == 0 ]; then
	USAGE
	exit -1
fi

echo

# Make Sure we found the EPICS utilities... ;-b
epicsck=`which caget 2>&1`
if [ $? != 0 ]; then
	echo "Error: EPICS Utilities Not Found...! Check EPICS Path..."
	exit -999
fi

# Check for settings customization...
testonly=0
PRE="[NotSet]"
for arg in $* ; do
	# echo "arg=$arg"
	key=`echo "$arg" | awk -F = '{print $1}'`
	value=`echo "$arg" | awk -F = '{print $2}'`
	# echo "key=$key"
    # echo "value=$value"
	if [ "#$key#" == '#--beamline#' ]; then
		PRE="$value"
		echo -e "Setting EPICS PV Prefix to: $PRE\n"
	elif [ "#$key#" == '#--config#' ]; then
		SMSD_CONFIG="$value"
		echo -e "Using SMS Daemon Config File in:\n   $SMSD_CONFIG\n"
	elif [ "#$key#" == '#--repo#' ]; then
		CONFIG_REPO="$value"
		echo -e "Using Git Config Repository in:\n   $CONFIG_REPO\n"
	elif [ "#$key#" == '#--option#' ]; then
		command="option"
		opt_arg="$value"
		echo -e "Setting Command to: $command $opt_arg\n"
	elif [ "#$key#" == '#--testonly#' ]; then
		testonly=1
		echo -e "*** TEST RUN ONLY! ***\n\nNothing will change/commit!\n"
	elif [ "#$key#" == '#--help#' ]; then
		USAGE
		exit -1
	else
		command="$key"
		echo -e "Setting Command to: $command\n"
	fi
done

#
# Determine the Beamline Host, and thereby
# the EPICS PV Prefix and Git Config Repo Branch...
#

if [ ${PRE} == "[NotSet]" ]; then

	config_host=`hostname -A | sed 's/ /\n/g' | grep '^bl'`
	config_branch=`echo "$config_host" | sed 's/-.*//'`
	if [[ "$config_host" == "" || "$config_branch" == "" ]]; then
		echo -e "\nError: This is _Not_ a Beamline SMS Computer!\n"
		exit -90
	fi

	echo "Changing Configuration on Host ${config_host}."
	echo "(Git Config Repository Branch ${config_branch}.)"

	PRE=`echo "$config_branch" | tr '[:lower:]' '[:upper:]'`
	echo "Setting EPICS PV Prefix from Config Branch: ${PRE}."

else
	config_branch=`echo "${PRE}" | tr '[:upper:]' '[:lower:]'`
	echo -n "Setting Git Config Repository Branch "
	echo "from EPICS PV Prefix: ${config_branch}."
fi

echo

# Dump All Known SMS EPICS PVs...
if [[ "$command" == "status" \
		|| "$command" == "run_status" \
		|| "$command" == "data_status" \
		|| "$command" == "sys_status" ]]; then

	# Check to see if SMS is Up & Running and has Initialized EPICS PVs...
	# (Give the SMS plenty of time to reply, since it's Not multi-threaded.)
	caget $WAIT ${PRE}:SMS:Recording > /dev/null 2>&1
	if [ $? != 0 ]; then
		echo \
		"Error: $PRE SMS EPICS PVs Not Initialized... Is 'smsd' running?"
		exit -2
	fi

	if [[ "$command" == "status" \
			|| "$command" == "run_status" ]]; then

		caget $WAIT ${PRE}:SMS:Recording

		caget $WAIT ${PRE}:SMS:RunNumber

		caget $WAIT ${PRE}:SMS:Summary

		echo

		caget $WAIT -S ${PRE}:SMS:RunInfo:ProposalId
		caget $WAIT -S ${PRE}:SMS:RunInfo:ProposalTitle
		caget $WAIT -S ${PRE}:SMS:RunInfo:RunTitle
		caget $WAIT -S ${PRE}:SMS:RunInfo:Sample:Id
		caget $WAIT -S ${PRE}:SMS:RunInfo:Sample:Name
		caget $WAIT -S ${PRE}:SMS:RunInfo:Sample:Nature
		caget $WAIT -S ${PRE}:SMS:RunInfo:Sample:Formula
		caget $WAIT -S ${PRE}:SMS:RunInfo:Sample:Environment

		echo

		caget $WAIT ${PRE}:SMS:Marker:ScanIndex
		caget $WAIT ${PRE}:SMS:Marker:StartScan
		caget $WAIT ${PRE}:SMS:Marker:StopScan
		caget $WAIT -S ${PRE}:SMS:Marker:Comment
		caget $WAIT ${PRE}:SMS:Marker:Annotate
		caget $WAIT ${PRE}:SMS:Marker:RunComment

		echo

		caget $WAIT ${PRE}:SMS:Paused

		echo
	fi

	if [[ "$command" == "status" \
			|| "$command" == "data_status" ]]; then

		ndsvar="${PRE}:SMS:Control:NumDataSources"
		caget $WAIT $ndsvar
		if [ $? == 0 ]; then
			echo
			numDataSources=`caget $WAIT $ndsvar | grep $ndsvar \
				| awk '{print $2}'`
			# Count from 1...!
			for (( ds=1 ; ds <= numDataSources ; ds++ )); do
				echo "Data Source id=${ds}:"
				caget $WAIT -S ${PRE}:SMS:DataSource:${ds}:Name
				caget $WAIT ${PRE}:SMS:DataSource:${ds}:Enabled
				caget $WAIT -a ${PRE}:SMS:DataSource:${ds}:Connected
				caget $WAIT ${PRE}:SMS:DataSource:${ds}:ConnectRetry
				caget $WAIT ${PRE}:SMS:DataSource:${ds}:ConnectTimeout
				caget $WAIT ${PRE}:SMS:DataSource:${ds}:DataTimeout
				caget $WAIT ${PRE}:SMS:DataSource:${ds}:IgnoreEoP
				echo
			done
		fi
	fi

	if [[ "$command" == "status" \
			|| "$command" == "sys_status" ]]; then

		caget $WAIT ${PRE}:SMS:Control:NoEoPPulseBufferSize

		echo

		caget $WAIT -S ${PRE}:SMS:StorageManager:Poolsize
		caget $WAIT ${PRE}:SMS:StorageManager:Percent
		caget $WAIT ${PRE}:SMS:StorageManager:MaxBlocksAllowed

		echo

		caget $WAIT ${PRE}:SMS:STSClient:ConnectTimeout
		caget $WAIT ${PRE}:SMS:STSClient:ReconnectTimeout
		caget $WAIT ${PRE}:SMS:STSClient:TransientTimeout
		caget $WAIT ${PRE}:SMS:STSClient:MaxConnections
		caget $WAIT ${PRE}:SMS:STSClient:MaxRequeueCount
		caget $WAIT -S ${PRE}:SMS:STSClient:ServiceURI

		echo
	fi

# Set No End-of-Pulse Internal Pulse Buffer Size...
elif [ "$command" == "option" ]; then

	#
	# Parse Option Arg String into Pieces... ;-D
	#

	opt_id_str=`echo "$opt_arg" | awk -F ':' '{print $1}'`
	opt_id_type=`echo "$opt_id_str" | awk -F '[0-9]' '{print $1}'`
	echo "opt_id_str=$opt_id_str opt_id_type=$opt_id_type"

	opt_rest=`echo "$opt_arg" | awk -F ':' '{print $2}'`
	option=`echo "$opt_rest" | awk -F '[<>]' '{print $1}'`
	opt_value=`echo "$opt_arg" | awk -F '[<>]' '{print $2}'`
	echo "option=$option opt_value=$opt_value"

	echo "is_indexed=${is_indexed[$opt_id_type]}"
	if [ ${is_indexed[$opt_id_type]} == 1 ]; then
		opt_id_num=`echo "$opt_id_str" | sed "s/$opt_id_type//"`
		optId="${idName[$opt_id_type]}${opt_id_num}"
	else
		opt_id_num="-1"
		optId="${idName[$opt_id_type]}"
	fi
	echo "opt_id_num=$opt_id_num optId=$optId"

	# Identify Option, Set Option-Specific Parameters and Information...

	PV=""

	for i in $( seq 0 $(( num_options - 1 )) ) ; do
		if [[ "$opt_id_type" == "${option_id_type[$i]}"
				&& "$option" == "${option_name[$i]}" ]]; then
			PV="${option_pv[$i]}"
			opt_value_type="${option_value_type[$i]}"
			opt_label="${option_label[$i]}"
			break;
		fi
	done

	if [ "#$PV#" == '##' ]; then
		echo -e "\nError: Unknown Option [$option]...! Bailing...\n"
		exit -1
	fi

	echo "PV=$PV opt_label=$opt_label"

	echo -e "Setting Option ${optId}:${opt_label} to ${opt_value}.\n"

	#
	# Prompt for Live/Config Option Change Log Description Text [Required!]
	#

	echo "Please Enter Option Change Log Text for:"
	echo -e "   ${optId}:${opt_label}\n"
	echo -e "(Enter a Blank Line to Finish.)\n"

	LOG="$TMP_DIR/LiveConfig-${opt_id_str}-${option}-$$.txt"

	log_desc=""
	empty=1
	done=0

	while [ $done != 1 ]; do

		echo -n " > "
		read text_line

		if [ "$text_line" == "" ]; then
			if [ $empty != 1 ]; then
				done=1
			else
				echo \
				"(Option Change Log Must Be Non-Empty! Please Enter Log.)"
			fi
		else
			if [ $empty != 1 ]; then
				log_desc="$log_desc\n$text_line"
			else
				log_desc="$text_line"
			fi
			empty=0
		fi

	done

	echo -e "\nOption Change Log Description Text:\n" | tee -a $LOG

	echo -e "$log_desc\n" | tee -a $LOG

	any_change=0

	#
	# Get Current Live SMS Daemon Option Setting
	#

	echo

	do_live=1

	echo "Current Live SMS Daemon Setting (PV) for:"
	echo -e "   ${optId}:${opt_label}\n"
	live_current=`caget $WAIT ${PRE}:${PV} 2>&1`
	if [ $? != 0 ]; then
		echo -e "\n***Error Contacting SMS Daemon/Option PV...!\n"
		echo "Proceed with Live Config of:"
		echo -n "   ${optId}:${opt_label} (yes/No)? "
		read ckcont
		ckcont=`echo "$ckcont" | tr '[:upper:]' '[:lower:]'`
		if [[ "$ckcont" == "" || "$ckcont" == "n" \
				|| "$ckcont" == "no" ]]; then
			echo -e "\nExiting LiveConf at User's Request.\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -3
		fi
		# Continue, But Skip Live Option Setting...
		do_live=0
	else
		live_value=`echo $live_current | awk '{print $2}'`
		echo "   $live_current ($live_value)"
	fi

	#
	# Get Current SMS Daemon Config File Setting
	#

	echo

	do_config=1

	echo "Current SMS Daemon Config File Setting for:"
	echo "   ${optId}:${opt_label}"
	echo "   (in $SMSD_CONFIG)"

	config_list=`grep -n -e '^\[' -e "$option" $SMSD_CONFIG | grep -v ';'`
	config_size=`echo "$config_list" | wc | awk '{print $1}'`

	config_value=""
	config_line=""

	source_cnt=0

	id_name=""
	id_type=""
	id_num=0

	found=0

	for (( n=1 ; n <= config_size ; n++ )); do

		line=`echo "$config_list" | sed -n "${n}p"`
		# echo "config line $n = [$line]"

		line_num=`echo "$line" | awk -F ':' '{print $1}'`
		# echo "line_num=$line_num"

		line_rest=`echo "$line" | awk -F ':' '{print $2}'`
		# echo "line_rest=$line_rest"

		line_id=`echo "$line_rest" | awk -F '[][]' '{print $2}'`
		# echo "line_id=$line_id"

		# Option Line
		if [ "$line_id" == "" ]; then

			# echo "Config Option Line..."

			if [[ "$id_type" == "$opt_id_type" \
					&& "$id_num" == "$opt_id_num" ]]; then

				# echo "Match!"

				config_current_line="$line_rest"
				# echo "Matching Config File Line = ${config_current_line}."

				config_line="$line_num"
				# echo "Matching Config File Line Number = ${config_line}."

				config_value=`echo "$line_rest" | awk -F '=' '{print $2}'`
				config_value=`echo "$config_value" | sed "s/ //g"`
				# echo -n "Config File Option "
				# echo "${optId}:${opt_label} = ${config_value}."

				id_name="$line_id_name"

				found=$(( found + 1 ))

			fi

		# SMS or Source Line
		else
			id_type=`echo "$line_id" | awk '{print $1}'`
			if [ "$id_type" == "source" ]; then
				source_name=`echo "$line_id" | sed "s/^source //"`
				line_id_name=" (${source_name})"
				source_cnt=$(( source_cnt + 1 ))
				id_num="$source_cnt"
				# echo "Source #${source_cnt}: ${source_name} Section."
			elif [ "$id_type" == "sms" ]; then
				line_id_name=""
				id_num="-1"
				# echo "SMS Section."
			fi
		fi

	done

	opt_str="${optId}:${opt_label}${id_name} to ${opt_value}"

	if [[ $found == 0 ]]; then
		echo -e "\nWARNING: Active Option Setting Not Found!"
		echo "Cannot Automatically Update Configuration File... ;-Q"
		echo "   ${opt_str}"
		do_config=0
	elif [[ $found > 1 ]]; then
		echo -e "\nWARNING: *Multiple* Active Non-Source Option Settings!"
		echo "Cannot Automatically Update Configuration File... ;-Q"
		echo "   ${opt_str}"
		do_config=0
	fi

	if [ "$do_config" == 1 ]; then
		echo -e "\nCurrent Config File Option at Line ${config_line}:"
		echo "   ${optId}:${opt_label}${id_name} = ${config_value}."
	fi

	#
	# Update Live SMS Daemon Option Setting
	#

	echo

	if [ $do_live != 1 ]; then
		echo "Skipping Live SMS Daemon Option Setting, At User's Request."
	elif [ "$opt_value" == "$live_value" ]; then
		echo "Live SMS Daemon _Already Has_ Option Set! :-)"
		echo "   ${optId}:${opt_label}${id_name} = ${opt_value}"
		echo -e "\nDone."
	else

		echo "Proceed to Set Live Option:"
		echo -n "   ${opt_str} (yes/No)? "
		read ckset
		ckset=`echo "$ckset" | tr '[:upper:]' '[:lower:]'`
		if [[ "$ckset" == "" || "$ckset" == "n" || "$ckset" == "no" ]]; then
			echo -e "\nExiting LiveConf at User's Request.\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -3
		fi

		echo "Setting Live SMS Daemon Option:"
		echo "   ${opt_str} ($opt_value)"
		if [ $testonly == 1 ]; then
			echo "[TESTONLY] caput ${PRE}:${PV} $opt_value"
		else
			caput "${PRE}:${PV}" "$opt_value"
		fi
		if [ $? != 0 ]; then
			echo "Error Setting ${optId}:${opt_label}${id_name}...!"
			echo "Bailing..."
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -99
		fi

		any_change=$(( any_change + 1 ))

	fi

	#
	# Update Current SMS Daemon Config File Setting
	#

	echo

	if [ $do_config != 1 ]; then
		echo "Skipping Config File Option Set."
	elif [ "$opt_value" == "$config_value" ]; then
		echo "SMS Daemon Config _Already Has_ Option Set! :-)"
		echo "   ${optId}:${opt_label}${id_name} = ${opt_value}"
		echo -e "\nDone."
	else

		echo "Proceed to Set Config File Option:"
		echo -n "   ${opt_str} (yes/No)? "
		read ckset
		ckset=`echo "$ckset" | tr '[:upper:]' '[:lower:]'`
		if [[ "$ckset" == "" || "$ckset" == "n" || "$ckset" == "no" ]]; then
			echo -e "\nExiting LiveConf at User's Request.\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -3
		fi

		echo
		echo "Setting SMS Daemon Config File Option:"
		echo "   ${opt_str}"

		tmpconfig="$TMP_DIR/smsd.conf-liveconf.$$"

		new_config_line=`echo "$config_current_line" \
			| sed "s/$config_value/$opt_value/"`

		sed "${config_line}s/^$config_current_line/$new_config_line/" \
			$SMSD_CONFIG > $tmpconfig

		echo -e "\nModified Config File Differences:"
		diff -c $SMSD_CONFIG $tmpconfig
		echo

		echo -n "Replace Current Config File (yes/No)? "
		read ckrepl
		ckrepl=`echo "$ckrepl" | tr '[:upper:]' '[:lower:]'`
		if [[ "$ckrepl" == "" || "$ckrepl" == "n" \
				|| "$ckrepl" == "no" ]]; then
			echo -e "\nSkipping Config File Update at User's Request!\n"
			do_config=0
		else

			if [ $testonly == 1 ]; then
				echo \
				"[TESTONLY] sudo -u $CONFIG_USER cp $tmpconfig $SMSD_CONFIG"
			else
				sudo -u $CONFIG_USER cp $tmpconfig $SMSD_CONFIG
			fi
			if [ $? != 0 ]; then
				echo -e "\nError Copying New Config File to Production:\n"
				/bin/ls -l $tmpconfig
				echo
				/bin/ls -l $SMSD_CONFIG
				echo
				/bin/ls -l $LOG
				/bin/cat $LOG
				exit -5
			fi

			any_change=$(( any_change + 1 ))

		fi

		/bin/rm $tmpconfig

	fi

	#
	# Commit Config File Change to Git Repository
	#

	echo

	if [ $do_config != 1 ]; then
		echo "Skipping Git Config Repository Update."
	elif [ $any_change == 0 ]; then
		echo "No Live/Config Options Changed; Nothing to Commit/Log."
	else

		echo "Committing Change to Git Config Repository in:"
		echo -e "   $CONFIG_REPO\n"

		# Go to the Git Config Repo Directory... (if it exists ;-)
		cd $CONFIG_REPO
		if [ $? != 0 ]; then
			echo -e "\nError: Git Config Repository Path Invalid!\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -4
		fi

		# Make sure we're in the "right" repo...? ;-)
		config_repo=`git config --get remote.origin.url`
		repo_ck=`echo "$config_repo" | grep 'config$' \
			| wc | awk '{print $1}'`
		if [ "$repo_ck" != 1 ]; then
			echo -e "\nError: This is _Not_ the Git Config Repository!\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -5
		fi

		# Check Out Beamline Git Config Branch...
		echo "Checking Out Beamline Git Config Branch: ${config_branch}."
		git checkout $config_branch
		if [ $? != 0 ]; then
			echo -e \
				"\nError Checking Out Git Config Branch $config_branch!\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -7
		fi

		# "Freshen Up" the Local Config Repo Copy... ;-)
		git pull
		git diff
		git status

		echo

		# Prompt for Actually Updating the Git Config Repo...
		echo -n "Proceed to Update Git Config Repository (yes/No)? "
		read ckupdate
		ckupdate=`echo "$ckupdate" | tr '[:upper:]' '[:lower:]'`
		if [[ "$ckupdate" == "" || "$ckupdate" == "n" \
				|| "$ckupdate" == "no" ]]; then
			echo -e \
			"\nSkipping Git Config Repository Update at User's Request!\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -3
		fi

		# Update the SMS Daemon Config File in the Git Config Repo...
		if [ $testonly == 1 ]; then
			echo "[TESTONLY] cp -i $SMSD_CONFIG $REPO_CONFIG"
		else
			cp -i $SMSD_CONFIG $REPO_CONFIG
		fi
		if [ $? != 0 ]; then
			echo -e \
				"\nError Copying Latest Config File into Git Config Repo!\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -8
		fi

		# Show what changed...
		echo -e "\nGit Repo Config File Differences:"
		git diff
		echo

		# Prompt for Committing the Config File Change...
		echo -n "Proceed with Git Config Commit (yes/No)? "
		read ckcommit
		ckcommit=`echo "$ckcommit" | tr '[:upper:]' '[:lower:]'`
		if [[ "$ckcommit" == "" || "$ckcommit" == "n" \
				|| "$ckcommit" == "no" ]]; then
			echo -e "\nSkipping Config File Commit at User's Request!\n"
			/bin/ls -l $LOG
			/bin/cat $LOG
			exit -3
		fi

		# Commit the Config File Change...
		if [ $testonly == 1 ]; then echo -n "[TESTONLY] "; fi
		echo -e "Set SMS Live/Config Option:\n   ${opt_str}\n\n$log_desc\n"
		echo "git commit -F - ."

		if [ $testonly != 1 ]; then
			echo -e \
			"Set SMS Live/Config Option:\n   ${opt_str}\n\n$log_desc\n" \
				| git commit -F - .
		fi
		commit_ok=$?

		if [ $commit_ok != 0 ]; then
			echo -e "\nError Committing Config Update! ($commit_ok)\n"
		fi

		# Now Push All the Config Commits to Origin

		echo -e "\nPushing Config Commits to Origin:"
		echo "git push"
		git push
		push_ok=$?

		if [ $push_ok != 0 ]; then
			echo -e "\nError Pushing Config Update to Origin! ($push_ok)\n"
		fi

	fi

	#
	# Cleanup Temporary Log File...
	#

	echo 

	/bin/rm $LOG

# Done
fi

