#!/bin/bash
#
# (Cron) Script to Monitor Local SMS Daemon Executable
#
# Track things like Memory/CPU Usage, as well as Note If/When SMSD Fails!
# (and maybe even notify via email or text message on a crash...! :-)
#

host=`hostname`
#echo "host=$host"

host_short=`echo $host | awk -F '.' '{print $1}'`
#echo "host_short=$host_short"

LOGFILE="$HOME/smsd_mon/smsd_mon.$host_short.log"
LOGLOGFILE="$HOME/smsd_mon/smsd_mon.$host_short-log.log"

SMSD_USER="snsdata"
SMSD="smsd"

SMSD_LOG="/var/log/smsd.log"

PROG="smsd_mon"

#
# Parse Command Line Options... ;-)
#

do_notify=1

for arg in "$@" ; do

	key=`echo "$arg" | awk -F = '{print $1}'`
	value=`echo "$arg" | awk -F = '{print $2}'`

	if [ "#$key#" == '#--no_notify#' ]; then
		do_notify=0
	elif [ "#$key#" == '#--smsd_user#' ]; then
		SMSD_USER="$value"
	elif [ "#$key#" == '#--help#' ]; then
		echo "usage:  smsd_mon [--no_notify] [--smsd_user=y8y]"
		exit 0
	fi

done

#
# Get SMS Daemon process status...
#

date=`date`
#echo "date=$date"

status=`ps augxww | grep $SMSD | grep -v -e $PROG -e grep | grep $SMSD_USER`
#echo "status=$status"

if [ "#$status#" == '##' ]; then

	if [ $do_notify == 1 ]; then
		echo \
		"Error on ${host}: SMS Daemon $SMSD Not Running as User $SMSD_USER!"
		exit -1
	else
		# Just Exit Cleanly, Nothing to log here... ;-D
		exit 0
	fi
fi

# Extract statistics of interest

log="$date $host $SMSD as ${SMSD_USER}:\n  "

pid=`echo "$status" | awk '{print $2}'`
#echo "pid=$pid"
log="$log pid=$pid"

cpuP=`echo "$status" | awk '{print $3}'`
#echo "cpuP=$cpuP"
log="$log cpu=${cpuP}%"

memP=`echo "$status" | awk '{print $4}'`
#echo "memP=$memP"
log="$log mem=${memP}%"

vsz=`echo "$status" | awk '{print $5}'`
#echo "vsz=$vsz"
log="$log vsz=${vsz}K"

rss=`echo "$status" | awk '{print $6}'`
#echo "rss=$rss"
log="$log rss=${rss}K"

start=`echo "$status" | awk '{print $9}'`
#echo "start=$start"
log="$log start=$start"

cpuT=`echo "$status" | awk '{print $10}'`
#echo "cpuT=$cpuT"
log="$log time=$cpuT"

#
# Dump SMS Daemon Status Snapshot into Log file...
#

echo -e "$log" >> $LOGFILE

#
# Check on the SMS Daemon Log File size/usage...
#

hour=`echo $date | awk '{print $4}' | awk -F ":" '{print $1}' \
	| sed 's/^0//g'`
#echo "hour=$hour"
min=`echo $date | awk '{print $4}' | awk -F ":" '{print $2}' \
	| sed 's/^0//g'`
#echo "min=$min"

# Only check once or twice per day maybe...?
if [[ ( $hour -eq 10 || $hour -eq 16 ) && $min -eq 0 ]]; then

	log_bytes=`/bin/ls -l $SMSD_LOG | awk '{print $5}'`
	log_hbytes=`/bin/ls -lh $SMSD_LOG | awk '{print $5}'`

	touch $LOGLOGFILE
	echo "$date $host $SMSD_LOG = $log_hbytes" >> $LOGLOGFILE

	smsd_top_logdir=`echo $SMSD_LOG | awk -F '/' '{print "/"$2}'`

	log_used=`df $SMSD_LOG | grep $smsd_top_logdir | awk '{print $(NF-3)}'`
	#echo "log_used=$log_used"
	log_avail=`df $SMSD_LOG | grep $smsd_top_logdir | awk '{print $(NF-2)}'`
	#echo "log_avail=$log_avail"

	pct_log=$(( $log_bytes * 100 / ( $log_used * 1000 ) ))
	#echo "pct_log=$pct_log"

	pct_used=$(( $log_used * 100 / $log_avail ))
	#echo "pct_used=$pct_used"

	echo \
	"   Log is $log_bytes = $pct_log% of usage, Disk is $pct_used% full." \
		>> $LOGLOGFILE

	# Seemed like a good idea at the time... ;-D
	# if [[ $pct_log -gt 80 ]]; then
	# 	echo "Error on ${host}: SMS Daemon Log is $pct_log% of Usage!"
	# 	echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
	# 	exit -2
	# fi

	if [[ $pct_used -gt 80 ]]; then
		echo "Error on ${host}: $smsd_top_logdir is $pct_used% Full!"
		echo "   $SMSD_LOG $log_bytes ($log_hbytes)"
		exit -3
	fi
fi

