#!/bin/bash

ALT="" # for Alternate/Secondary SMS Deployments... ;-D

#
# Parse Command Line Options... ;-)
#

for arg in "$@" ; do

	key=`echo "$arg" | awk -F = '{print $1}'`
	value=`echo "$arg" | awk -F = '{print $2}'`

	if [[ "#$key#" == '#--alt#' ]]; then
		ALT="$value"
	elif [[ "#$key#" == '#--help#' || "#$key#" == '#-h#' ]]; then
		echo "usage:  smsm [--alt=\"-mon\"]"
		exit 0
	fi

done

less /var/log/smsd${ALT}.log

