#!/bin/bash

if [ $# == 0 ]; then
	echo
	echo "usage:  check_xml <beamline.xml> [ <foo.xml> . . . ]"
	echo
	exit -1
fi

failures=0

for f in $* ; do

	echo
	echo "Checking XML Formatting of:"
	echo "   [$f]"

	xmllint --noout $f

	status=$?

	if [ $status != 0 ]; then
		echo "ERROR: Invalid Format ($status)!"
		(( failures++ ))
	else
		echo "Format Ok."
	fi

done

echo
echo "$failures Invalid XML Files Detected."
echo

