# Capture Critical ADARA SMS Messages - For ADARA Summary/Monitor Analysis

if $msg contains "ERROR SMS"
		or $msg contains "PVSD ERROR"
		or $msg contains "STC Error"
		or $msg contains "STC failed"
		or $msg contains "Unexpected input"
		or $msg contains "OversizePkt" then {
	action(type="ompipe" pipe="/etc/rsyslog.pipes/criticalMessages"
		Template="RSYSLOG_TraditionalFileFormat")
}

