#!/bin/bash
#
# ADARA Summary
#
# Process ADARA "Critical ADARA Syslog Error" Emails
# to Collect Statistics on the Number and Type of Various Errors.
# (and Save Jeeem some Time in scouring all these notification emails! ;-D)
#

S="[[:space:]]"

#
# Dump Usage
#

USAGE()
{
	echo "usage:  adara_summary [FILE1 [FILE2 . . . ]] [-h|--help]"
	echo

	echo "where:"
	echo

	echo "   FILE1, FILE2...   = list of captured email files to summarize"
	echo "                       (else reads from stdin...)"
	echo "   -h|--help         = display this usage information"
	echo
}

FileList=""

for arg in "$@" ; do
	# echo "arg=$arg"
	key=`echo "$arg" | awk -F = '{print $1}'`
	value=`echo "$arg" | awk -F = '{print $2}'`
	# echo "key=$key"
	# echo "value=$value"
	if [ "#$key#" == '#--help#' ]; then
		USAGE
		exit 0
	else
		if [[ -f $key ]]; then
			#echo -e "Adding to File List:\n   [${key}]"
			FileList="${FileList} ${key}"
		else
			echo -e "\nError: Unknown Option/Unrecognized File:\n [${key}]"
			USAGE
			exit -1
		fi
	fi
done

#
# If No Input Files Specified, Read from Stdin...
#

if [[ -z "${FileList}" ]]; then
	echo "No Input Files Specified: Reading from /dev/stdin..."
	FileList="/dev/stdin"
fi

#
# Global Counters
#

HostList=""

declare -A nHostlogs

declare -A lastFileFrom

declare -A nHostSTSLdapLookupUserName
declare -A nHostSTSMoreThanOnePVValue
declare -A nHostSTSNoMatchingUnitsPV
declare -A nHostSTSVarValueSawtooth
declare -A nHostSTSVarValueTruncateNegTime
declare -A nHostSTSActiveMQException
declare -A nHostSTSComBusBroadcastError
declare -A nHostSTSComBusConnTimeout
declare -A nHostSTSComBusDisconnectError
declare -A nHostSTSComBusReconnectThread
declare -A nHostSTSUpdatingRunInfo
declare -A nHostSTSDetBankSetConfigErr
declare -A nHostSTSDetBankSetRestrictEv
declare -A nHostSTSDuplicatePulse
declare -A nHostSTSOversizePkt

declare -A nHostSMSDRunAwayDataSource
declare -A nHostSMSDMissingRingPeriod
declare -A nHostSMSDSystemNOTReady
declare -A nHostSMSDSystemReady
declare -A nHostSMSDDataSourceTimedOut
declare -A nHostSMSDDataSourceTimedOutRetry
declare -A nHostSMSDNoRTDLForPulse
declare -A nHostSMSDNoMorePulsesForCorrect
declare -A nHostSMSDCorrectPChargeVeto
declare -A nHostSMSDLocalSAWTOOTHRTDL
declare -A nHostSMSDLocalSAWTOOTHData
declare -A nHostSMSDGlobalSAWTOOTH
declare -A nHostSMSDPulseNoRegEvent
declare -A nHostSMSDFirstNewEventSource
declare -A nHostSMSDLastEventSource
declare -A nHostSMSDLiveClientLogs
declare -A nHostSMSDActiveMQException
declare -A nHostSMSDComBusBroadcastError
declare -A nHostSMSDComBusConnTimeout
declare -A nHostSMSDComBusDisconnectError
declare -A nHostSMSDComBusReconnectThread
declare -A nHostSMSDOversizePkt

declare -A nHostPVSDINITHUNG
declare -A nHostPVSDDeviceRecoveredFromHung
declare -A nHostPVSDEPICSCAException
declare -A nHostPVSDActiveMQException
declare -A nHostPVSDComBusBroadcastError
declare -A nHostPVSDComBusConnTimeout
declare -A nHostPVSDComBusDisconnectError
declare -A nHostPVSDComBusReconnectThread
declare -A nHostPVSDDefiningNewDevice
declare -A nHostPVSDUndefineDevice
declare -A nHostPVSDUndefineDevicePkt
declare -A nHostPVSDMakePvNamesUnique
declare -A nHostPVSDAssignPVID
declare -A nHostPVSDInactiveDeviceID
declare -A nHostPVSDDeviceNotYetDefined
declare -A nHostPVSDSubscriptionCreated
declare -A nHostPVSDClearingSubscription
declare -A nHostPVSDConnectedToSMSClient
declare -A nHostPVSDInitialSendsComplete
declare -A nHostPVSDAlive
declare -A nHostPVSDPartial
declare -A nHostPVSDHung
declare -A nHostPVSDOversizePkt

declare -A nHostDASMONDFailedToConnSMS
declare -A nHostDASMONDActiveMQException
declare -A nHostDASMONDComBusBroadcastError
declare -A nHostDASMONDComBusConnTimeout
declare -A nHostDASMONDComBusDisconnectError
declare -A nHostDASMONDComBusReconnectThread
declare -A nHostDASMONDOversizePkt

nUnknownLogs=0
nUnknownDASMOND=0
nUnknownSMSD=0
nUnknownPVSD=0
nUnknownSTS=0

nDASMOND=0
nSMSD=0
nPVSD=0
nSTS=0

nemail=0
nblank=0
nhdr=0
nlog=0

#
# Parse One Log Message
#

PARSE_LOG()
{
	log="$1"

	#echo "ParseLog=[$log]"

	host=`echo "$log" | awk '{print $1}'`
	#echo "Host=[$host]"

	ckhost=`echo "${HostList}" | grep -c "$host"`
	if [[ $ckhost == 1 ]]; then
		nHostlogs[$host]=$(( nHostlogs[$host] + 1 ))
	else

		HostList="${HostList} $host"

		nHostlogs[$host]=1

		nHostSTSLdapLookupUserName[$host]=0
		nHostSTSMoreThanOnePVValue[$host]=0
		nHostSTSNoMatchingUnitsPV[$host]=0
		nHostSTSVarValueSawtooth[$host]=0
		nHostSTSVarValueTruncateNegTime[$host]=0
		nHostSTSActiveMQException[$host]=0
		nHostSTSComBusBroadcastError[$host]=0
		nHostSTSComBusConnTimeout[$host]=0
		nHostSTSComBusDisconnectError[$host]=0
		nHostSTSComBusReconnectThread[$host]=0
		nHostSTSUpdatingRunInfo[$host]=0
		nHostSTSDetBankSetConfigErr[$host]=0
		nHostSTSDetBankSetRestrictEv[$host]=0
		nHostSTSDuplicatePulse[$host]=0
		nHostSTSOversizePkt[$host]=0

		nHostSMSDRunAwayDataSource[$host]=0
		nHostSMSDMissingRingPeriod[$host]=0
		nHostSMSDSystemNOTReady[$host]=0
		nHostSMSDSystemReady[$host]=0
		nHostSMSDDataSourceTimedOut[$host]=0
		nHostSMSDDataSourceTimedOutRetry[$host]=0
		nHostSMSDNoRTDLForPulse[$host]=0
		nHostSMSDNoMorePulsesForCorrect[$host]=0
		nHostSMSDCorrectPChargeVeto[$host]=0
		nHostSMSDLocalSAWTOOTHRTDL[$host]=0
		nHostSMSDLocalSAWTOOTHData[$host]=0
		nHostSMSDGlobalSAWTOOTH[$host]=0
		nHostSMSDPulseNoRegEvent[$host]=0
		nHostSMSDFirstNewEventSource[$host]=0
		nHostSMSDLastEventSource[$host]=0
		nHostSMSDLiveClientLogs[$host]=0
		nHostSMSDActiveMQException[$host]=0
		nHostSMSDComBusBroadcastError[$host]=0
		nHostSMSDComBusConnTimeout[$host]=0
		nHostSMSDComBusDisconnectError[$host]=0
		nHostSMSDComBusReconnectThread[$host]=0
		nHostSMSDOversizePkt[$host]=0

		nHostPVSDINITHUNG[$host]=0
		nHostPVSDDeviceRecoveredFromHung[$host]=0
		nHostPVSDEPICSCAException[$host]=0
		nHostPVSDActiveMQException[$host]=0
		nHostPVSDComBusBroadcastError[$host]=0
		nHostPVSDComBusConnTimeout[$host]=0
		nHostPVSDComBusDisconnectError[$host]=0
		nHostPVSDComBusReconnectThread[$host]=0
		nHostPVSDDefiningNewDevice[$host]=0
		nHostPVSDUndefineDevice[$host]=0
		nHostPVSDUndefineDevicePkt[$host]=0
		nHostPVSDMakePvNamesUnique[$host]=0
		nHostPVSDAssignPVID[$host]=0
		nHostPVSDInactiveDeviceID[$host]=0
		nHostPVSDDeviceNotYetDefined[$host]=0
		nHostPVSDSubscriptionCreated[$host]=0
		nHostPVSDClearingSubscription[$host]=0
		nHostPVSDConnectedToSMSClient[$host]=0
		nHostPVSDInitialSendsComplete[$host]=0
		nHostPVSDAlive[$host]=0
		nHostPVSDPartial[$host]=0
		nHostPVSDHung[$host]=0
		nHostPVSDOversizePkt[$host]=0

		nHostDASMONDFailedToConnSMS[$host]=0
		nHostDASMONDActiveMQException[$host]=0
		nHostDASMONDComBusBroadcastError[$host]=0
		nHostDASMONDComBusConnTimeout[$host]=0
		nHostDASMONDComBusDisconnectError[$host]=0
		nHostDASMONDComBusReconnectThread[$host]=0
		nHostDASMONDOversizePkt[$host]=0

	fi
	#echo "HostLogCount[$host]=${nHostlogs[$host]}"

	app=`echo "$log" | awk '{print $2}' | sed "s/:$//"`
	#echo "App=[$app]"

	known=1

	if [[ "$app" == "sts" ]]; then

		nSTS=$(( nSTS + 1 ))

		# Strip Off STS PID and Error Prefix...
		if [[ "$log" =~ sts:${S}STS${S}Error: ]]; then
			log=`echo "$log" | \
			awk '{for(i=6;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`
		else
			log=`echo "$log" | \
			awk '{for(i=4;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`
		fi

		# "stsLdapLookupUserName()" Log
		if [[ "$log" =~ stsLdapLookupUserName ]]; then
			#echo "LDAP Lookup User Name..."
			nHostSTSLdapLookupUserName[$host]=$(( \
				nHostSTSLdapLookupUserName[$host] + 1 ))

		# "More Than 1 PV Value for..." Log
		elif [[ "$log" =~ More${S}Than${S}1${S}PV${S}Value${S}for ]]; then
			#echo "More Than 1 PV Value for..."
			nHostSTSMoreThanOnePVValue[$host]=$(( \
				nHostSTSMoreThanOnePVValue[$host] + 1 ))

		# "No Matching Units PV Found..." Log
		elif [[ "$log" =~ No${S}Matching${S}Units${S}PV${S}Found ]]; then
			#echo "No Matching Units PV Found..."
			nHostSTSNoMatchingUnitsPV[$host]=$(( \
				nHostSTSNoMatchingUnitsPV[$host] + 1 ))

		# "Variable Value Update SAWTOOTH" Log
		elif [[ "$log" =~ Variable${S}Value${S}Update${S}SAWTOOTH ]]; then
			#echo "Variable Value Update SAWTOOTH..."
			nHostSTSVarValueSawtooth[$host]=$(( \
				nHostSTSVarValueSawtooth[$host] + 1 ))

		# "Truncate Negative Variable Value Update Time" Log
		elif [[ "$log" =~ \
			Truncate${S}Negative${S}Variable${S}Value${S}Update${S}Time \
		]]; then
			#echo "Variable Value Update SAWTOOTH..."
			nHostSTSVarValueTruncateNegTime[$host]=$(( \
				nHostSTSVarValueTruncateNegTime[$host] + 1 ))

		# "(ComBus) ActiveMQ Exception Listener Called" Log
		elif [[ "$log" =~ \
				ActiveMQ${S}Exception${S}Listener${S}Called ]]; then
			#echo "ActiveMQ Exception Listener Called..."
			nHostSTSActiveMQException[$host]=$(( \
				nHostSTSActiveMQException[$host] + 1 ))

		# "(ComBus) Error Broadcasting Message" Log
		elif [[ "$log" =~ \
				broadcast\(\):${S}Error${S}Broadcasting${S}Message ]]; then
			#echo "ComBus Error Broadcasting Message..."
			nHostSTSComBusBroadcastError[$host]=$(( \
				nHostSTSComBusBroadcastError[$host] + 1 ))

		# "ComBus Connection Timeout for Domain" Log
		elif [[ "$log" =~ \
				ComBus${S}Connection${S}Timeout${S}for${S}Domain ]]; then
			#echo "ComBus Connection Timeout for Domain..."
			nHostSTSComBusConnTimeout[$host]=$(( \
				nHostSTSComBusConnTimeout[$host] + 1 ))

		# "(ComBus) Error Disconnecting Message Producers/Consumers" Log
		elif [[ "$log" =~ \
			Error${S}Disconnecting${S}Message${S}Producers/Consumers ]]; \
		then
			#echo "ComBus Error Disconnecting Message Producers/Consumers"
			nHostSTSComBusDisconnectError[$host]=$(( \
				nHostSTSComBusDisconnectError[$host] + 1 ))

		# "(ComBus) Reconnect Thread" Logs
		elif [[ "$log" =~ ComBus:${S}reconnectThread\(\) ]]; then
			#echo "ComBus Reconnect Thread..."
			nHostSTSComBusReconnectThread[$host]=$(( \
				nHostSTSComBusReconnectThread[$host] + 1 ))

		# "Updating RunInfo" Log
		elif [[ "$log" =~ Updating${S}RunInfo ]]; then
			#echo "Updating RunInfo..."
			nHostSTSUpdatingRunInfo[$host]=$(( \
				nHostSTSUpdatingRunInfo[$host] + 1 ))

		# "Detector Bank Set Config Error" Log
		elif [[ "$log" =~ \
			Detector${S}Bank${S}Set${S}[[:alnum:]]+${S}Config${S}Error \
		]]; then
			#echo "Detector Bank Set Config Error..."
			nHostSTSDetBankSetConfigErr[$host]=$(( \
				nHostSTSDetBankSetConfigErr[$host] + 1 ))

		# "Restricting Detector Bank Set to Event Mode" Log
		elif [[ "$log" =~ \
			Restricting${S}Detector${S}Bank${S}Set${S}to${S}Event${S}Mode \
		]]; then
			#echo "Restricting Detector Bank Set to Event Mode..."
			nHostSTSDetBankSetRestrictEv[$host]=$(( \
				nHostSTSDetBankSetRestrictEv[$host] + 1 ))

		# "Duplicate Pulse" Log
		elif [[ "$log" =~ Duplicate${S}Pulse ]]; then
			#echo "Duplicate Pulse..."
			nHostSTSDuplicatePulse[$host]=$(( \
				nHostSTSDuplicatePulse[$host] + 1 ))

		# "OversizePkt" Log
		elif [[ "$log" =~ OversizePkt ]]; then
			#echo "OversizePkt..."
			nHostSTSOversizePkt[$host]=$(( \
				nHostSTSOversizePkt[$host] + 1 ))

		# Unknown Log Message
		else
			nUnknownSTS=$(( nUnknownSTS + 1 ))
			known=0
		fi

	elif [[ "$app" == "smsd" ]]; then

		nSMSD=$(( nSMSD + 1 ))

		# Strip Off SMS Error Prefix...
		if [[ "$log" =~ smsd:${S}ERROR ]]; then
			log=`echo "$log" | \
			awk '{for(i=4;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`
		else
			log=`echo "$log" | \
			awk '{for(i=3;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`
		fi

		# "Run-Away Data Source" Log
		if [[ "$log" =~ Run-Away${S}Data${S}Source ]]; then
			#echo "Run-Away Data Source..."
			nHostSMSDRunAwayDataSource[$host]=$(( \
				nHostSMSDRunAwayDataSource[$host] + 1 ))

		# "Missing ring period" Log
		elif [[ "$log" =~ Missing${S}ring${S}period ]]; then
			#echo "Missing ring period..."
			nHostSMSDMissingRingPeriod[$host]=$(( \
				nHostSMSDMissingRingPeriod[$host] + 1 ))

		# "System NOT Ready" Log
		elif [[ "$log" =~ System${S}NOT${S}Ready ]]; then
			#echo "System NOT Ready..."
			nHostSMSDSystemNOTReady[$host]=$(( \
				nHostSMSDSystemNOTReady[$host] + 1 ))

		# "System Ready" Log
		elif [[ "$log" =~ System${S}Ready ]]; then
			#echo "System Ready..."
			nHostSMSDSystemReady[$host]=$(( \
				nHostSMSDSystemReady[$host] + 1 ))

		# "DataSource - WARNING: Timed out waiting for data from..." Log
		elif [[ "$log" =~ \
			WARNING:${S}Timed${S}out${S}waiting${S}for${S}data${S}from \
		]]; then
			#echo "WARNING: Timed out waiting for data from... (Retry)"
			nHostSMSDDataSourceTimedOutRetry[$host]=$(( \
				nHostSMSDDataSourceTimedOutRetry[$host] + 1 ))

		# "DataSource - Timed out waiting for data from..." Log
		elif [[ "$log" =~ \
				Timed${S}out${S}waiting${S}for${S}data${S}from ]]; then
			#echo "Timed out waiting for data from... (Past Retry)"
			nHostSMSDDataSourceTimedOut[$host]=$(( \
				nHostSMSDDataSourceTimedOut[$host] + 1 ))

		# "NO RTDL for Pulse" Log
		elif [[ "$log" =~ NO${S}RTDL${S}for${S}Pulse ]]; then
			#echo "NO RTDL for Pulse..."
			nHostSMSDNoRTDLForPulse[$host]=$(( \
				nHostSMSDNoRTDLForPulse[$host] + 1 ))

		# "No More Pulses for Proton Charge/Veto Flags Correction" Log
		elif [[ "$log" =~ \
			No${S}More${S}Pulses${S}for${S}Proton${S}Charge/Veto${S}Flags \
		]]; then
			#echo "No More Pulses for Proton Charge/Veto Flags Correction"
			nHostSMSDNoMorePulsesForCorrect[$host]=$(( \
				nHostSMSDNoMorePulsesForCorrect[$host] + 1 ))

		# "correctPChargeVeto" Log
		elif [[ "$log" =~ correctPChargeVeto ]]; then
			#echo "correctPChargeVeto..."
			nHostSMSDCorrectPChargeVeto[$host]=$(( \
				nHostSMSDCorrectPChargeVeto[$host] + 1 ))

		# "Local SAWTOOTH RTDL" Log
		elif [[ "$log" =~ Local${S}SAWTOOTH${S}RTDL ]]; then
			#echo "Local SAWTOOTH RTDL..."
			nHostSMSDLocalSAWTOOTHRTDL[$host]=$(( \
				nHostSMSDLocalSAWTOOTHRTDL[$host] + 1 ))

		# "Local SAWTOOTH RawData" Log
		elif [[ "$log" =~ Local${S}SAWTOOTH${S}RawData ]]; then
			#echo "Local SAWTOOTH RawData..."
			nHostSMSDLocalSAWTOOTHData[$host]=$(( \
				nHostSMSDLocalSAWTOOTHData[$host] + 1 ))

		# "Global SAWTOOTH Pulse" Log
		elif [[ "$log" =~ Global${S}SAWTOOTH${S}Pulse ]]; then
			#echo "Global SAWTOOTH Pulse..."
			nHostSMSDGlobalSAWTOOTH[$host]=$(( \
				nHostSMSDGlobalSAWTOOTH[$host] + 1 ))

		# "Pulse with No Registered Event Sources" Log
		elif [[ "$log" =~ \
				Pulse${S}with${S}No${S}Registered${S}Event${S}Sources ]]; \
		then
			#echo "Pulse with No Registered Event Sources..."
			nHostSMSDPulseNoRegEvent[$host]=$(( \
				nHostSMSDPulseNoRegEvent[$host] + 1 ))

		# "First New Event Source Registered" Log
		elif [[ "$log" =~ \
		  registerEventSource\(\):${S}First${S}New${S}Event${S}Source ]]; \
		then
			#echo "First New Event Source Registered..."
			nHostSMSDFirstNewEventSource[$host]=$(( \
				nHostSMSDFirstNewEventSource[$host] + 1 ))

		# "Last Event Source Unregistered" Log
		elif [[ "$log" =~ \
				unregisterEventSource\(\):${S}Last${S}Event${S}Source ]]; \
		then
			#echo "Last Event Source Unregistered..."
			nHostSMSDLastEventSource[$host]=$(( \
				nHostSMSDLastEventSource[$host] + 1 ))

		# Conglomerated "LiveClient" Logs
		elif [[ "$log" =~ SMS.LiveClient ]]; then
			#echo "LiveClient..."
			nHostSMSDLiveClientLogs[$host]=$(( \
				nHostSMSDLiveClientLogs[$host] + 1 ))

		# "(ComBus) ActiveMQ Exception Listener Called" Log
		elif [[ "$log" =~ \
				ActiveMQ${S}Exception${S}Listener${S}Called ]]; then
			#echo "ActiveMQ Exception Listener Called..."
			nHostSMSDActiveMQException[$host]=$(( \
				nHostSMSDActiveMQException[$host] + 1 ))

		# "(ComBus) Error Broadcasting Message" Log
		elif [[ "$log" =~ \
				broadcast\(\):${S}Error${S}Broadcasting${S}Message ]]; then
			#echo "ComBus Error Broadcasting Message..."
			nHostSMSDComBusBroadcastError[$host]=$(( \
				nHostSMSDComBusBroadcastError[$host] + 1 ))

		# "ComBus Connection Timeout for Domain" Log
		elif [[ "$log" =~ \
				ComBus${S}Connection${S}Timeout${S}for${S}Domain ]]; then
			#echo "ComBus Connection Timeout for Domain..."
			nHostSMSDComBusConnTimeout[$host]=$(( \
				nHostSMSDComBusConnTimeout[$host] + 1 ))

		# "(ComBus) Error Disconnecting Message Producers/Consumers" Log
		elif [[ "$log" =~ \
			Error${S}Disconnecting${S}Message${S}Producers/Consumers ]]; \
		then
			#echo "ComBus Error Disconnecting Message Producers/Consumers"
			nHostSMSDComBusDisconnectError[$host]=$(( \
				nHostSMSDComBusDisconnectError[$host] + 1 ))

		# "(ComBus) Reconnect Thread" Logs
		elif [[ "$log" =~ ComBus:${S}reconnectThread\(\) ]]; then
			#echo "ComBus Reconnect Thread..."
			nHostSMSDComBusReconnectThread[$host]=$(( \
				nHostSMSDComBusReconnectThread[$host] + 1 ))

		# "OversizePkt" Log
		elif [[ "$log" =~ OversizePkt ]]; then
			#echo "OversizePkt..."
			nHostSMSDOversizePkt[$host]=$(( \
				nHostSMSDOversizePkt[$host] + 1 ))

		# Unknown Log Message
		else
			nUnknownSMSD=$(( nUnknownSMSD + 1 ))
			known=0
		fi

	elif [[ "$app" == "pvsd" ]]; then

		nPVSD=$(( nPVSD + 1 ))

		# Strip Off PVSD ERROR Prefix...
		if [[ "$log" =~ pvsd:${S}PVSD${S}ERROR ]]; then
			log=`echo "$log" | \
			awk '{for(i=5;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`
		else
			log=`echo "$log" | \
			awk '{for(i=3;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`
		fi

		# "PVSD is Alive" (Partial/Hung Device Log)
		if [[ "$log" =~ ^PVSD${S}is${S}Alive${S}at${S} ]]; then
			#echo "PVSD is Alive at..."
			nHostPVSDAlive[$host]=$(( nHostPVSDAlive[$host] + 1 ))
			np=`echo "$log" | awk -F "[ ()]" '{print $12}'`
			#echo "npartial=$np"
			nHostPVSDPartial[$host]=$(( nHostPVSDPartial[$host] + np ))
			nh=`echo "$log" | awk -F "[ ()]" '{print $14}'`
			#echo "nhung=$nh"
			nHostPVSDHung[$host]=$(( nHostPVSDHung[$host] + nh ))

		# "INIT HUNG" Log
		elif [[ "$log" =~ INIT${S}HUNG,${S}Check${S}beamline.xml ]]; then
			#echo "INIT HUNG..."
			nHostPVSDINITHUNG[$host]=$(( nHostPVSDINITHUNG[$host] + 1 ))

		# "Device has recovered from hung state" Log
		elif [[ "$log" =~ \
				has${S}recovered${S}from${S}hung${S}state ]]; then
			#echo "Device has recovered from hung state..."
			nHostPVSDDeviceRecoveredFromHung[$host]=$(( \
				nHostPVSDDeviceRecoveredFromHung[$host] + 1 ))

		# "Caught EPICS Exception" Log
		elif [[ "$log" =~ \
			ca_exception_handler\(\):${S}Caught${S}EPICS${S}Exception ]]; \
		then
			#echo "Caught EPICS Exception..."
			nHostPVSDEPICSCAException[$host]=$(( \
				nHostPVSDEPICSCAException[$host] + 1 ))

		# "(ComBus) ActiveMQ Exception Listener Called" Log
		elif [[ "$log" =~ \
				ActiveMQ${S}Exception${S}Listener${S}Called ]]; then
			#echo "ActiveMQ Exception Listener Called..."
			nHostPVSDActiveMQException[$host]=$(( \
				nHostPVSDActiveMQException[$host] + 1 ))

		# "(ComBus) Error Broadcasting Message" Log
		elif [[ "$log" =~ \
				broadcast\(\):${S}Error${S}Broadcasting${S}Message ]]; then
			#echo "ComBus Error Broadcasting Message..."
			nHostPVSDComBusBroadcastError[$host]=$(( \
				nHostPVSDComBusBroadcastError[$host] + 1 ))

		# "ComBus Connection Timeout for Domain" Log
		elif [[ "$log" =~ \
				ComBus${S}Connection${S}Timeout${S}for${S}Domain ]]; then
			#echo "ComBus Connection Timeout for Domain..."
			nHostPVSDComBusConnTimeout[$host]=$(( \
				nHostPVSDComBusConnTimeout[$host] + 1 ))

		# "(ComBus) Error Disconnecting Message Producers/Consumers" Log
		elif [[ "$log" =~ \
			Error${S}Disconnecting${S}Message${S}Producers/Consumers ]]; \
		then
			#echo "ComBus Error Disconnecting Message Producers/Consumers"
			nHostPVSDComBusDisconnectError[$host]=$(( \
				nHostPVSDComBusDisconnectError[$host] + 1 ))

		# "(ComBus) Reconnect Thread" Logs
		elif [[ "$log" =~ ComBus:${S}reconnectThread\(\) ]]; then
			#echo "ComBus Reconnect Thread..."
			nHostPVSDComBusReconnectThread[$host]=$(( \
				nHostPVSDComBusReconnectThread[$host] + 1 ))

		# "Defining New Device" Log
		elif [[ "$log" =~ \
				defineDevice\(\):${S}Defining${S}New${S}Device ]]; then
			#echo "Defining New Device..."
			nHostPVSDDefiningNewDevice[$host]=$(( \
				nHostPVSDDefiningNewDevice[$host] + 1 ))

		# "Undefine Device" Log
		elif [[ "$log" =~ \
				undefineDevice\(\):${S}Un-defining${S}device ]]; then
			#echo "Undefine Device..."
			nHostPVSDUndefineDevice[$host]=$(( \
				nHostPVSDUndefineDevice[$host] + 1 ))

		# "Sending Empty Descriptor to *Undefine* Device" Log
		elif [[ "$log" =~ \
		  Sending${S}Empty${S}Descriptor${S}to${S}\*Undefine\*${S}Device \
		]]; then
			#echo "Undefine Device..."
			nHostPVSDUndefineDevicePkt[$host]=$(( \
				nHostPVSDUndefineDevicePkt[$host] + 1 ))

		# "Make PV Names Unique" Log
		elif [[ "$log" =~ ConfigManager::makePvNamesUnique\(\) ]]; then
			#echo "Make PV Names Unique..."
			nHostPVSDMakePvNamesUnique[$host]=$(( \
				nHostPVSDMakePvNamesUnique[$host] + 1 ))

		# "Assign PV ID" Log
		elif [[ "$log" =~ assign${S}PV${S}ID ]]; then
			#echo "Assign PV ID..."
			nHostPVSDAssignPVID[$host]=$(( \
				nHostPVSDAssignPVID[$host] + 1 ))

		# "Inactive Device ID" Log
		elif [[ "$log" =~ \
			configFileMonitorThread\(\):${S}Inactive${S}Device${S}ID ]]; \
		then
			#echo "Inactive Device ID..."
			nHostPVSDInactiveDeviceID[$host]=$(( \
				nHostPVSDInactiveDeviceID[$host] + 1 ))

		# "Device Not Yet Defined" Log
		elif [[ "$log" =~ \
			epicsEventHandler\(\):${S}Device${S}Not${S}Yet${S}Defined ]]; \
		then
			#echo "Device Not Yet Defined..."
			nHostPVSDDeviceNotYetDefined[$host]=$(( \
				nHostPVSDDeviceNotYetDefined[$host] + 1 ))

		# "Subscription created" Log
		elif [[ "$log" =~ \
			epicsConnectionHandler\(\):${S}Subscription${S}created ]]; then
			#echo "Subscription Created..."
			nHostPVSDSubscriptionCreated[$host]=$(( \
				nHostPVSDSubscriptionCreated[$host] + 1 ))

		# "Clearing subscription" Log
		elif [[ "$log" =~ \
			epicsConnectionHandler\(\):${S}Clearing${S}subscription ]]; \
		then
			#echo "Clearing Subscription..."
			nHostPVSDClearingSubscription[$host]=$(( \
				nHostPVSDClearingSubscription[$host] + 1 ))

		# "Connected to ADARA SMS Client" Log
		elif [[ "$log" =~ Connected${S}to${S}ADARA${S}SMS${S}Client ]]; \
		then
			#echo "Connected to ADARA SMS Client..."
			nHostPVSDConnectedToSMSClient[$host]=$(( \
				nHostPVSDConnectedToSMSClient[$host] + 1 ))

		# "Initial Sends Complete to ADARA SMS Client" Log
		elif [[ "$log" =~ \
			Initial${S}Sends${S}Complete${S}to${S}ADARA${S}SMS ]]; then
			#echo "Initial Sends Complete to ADARA SMS..."
			nHostPVSDInitialSendsComplete[$host]=$(( \
				nHostPVSDInitialSendsComplete[$host] + 1 ))

		# "OversizePkt" Log
		elif [[ "$log" =~ OversizePkt ]]; then
			#echo "OversizePkt..."
			nHostPVSDOversizePkt[$host]=$(( \
				nHostPVSDOversizePkt[$host] + 1 ))

		# Unknown Log Message
		else
			nUnknownPVSD=$(( nUnknownPVSD + 1 ))
			known=0
		fi

	elif [[ "$app" == "dasmon" ]]; then

		nDASMOND=$(( nDASMOND + 1 ))

		# Strip Off DASMOND Prefix...
		log=`echo "$log" | \
			awk '{for(i=3;i<NF;i++)printf("%s ",$(i));printf("%s",$NF);}'`

		# "Failed to Connect to SMS" Log
		if [[ "$log" =~ Failed${S}to${S}Connect${S}to${S}SMS${S}at ]]; then
			#echo "Failed to Connect to SMS..."
			nHostDASMONDFailedToConnSMS[$host]=$(( \
				nHostDASMONDFailedToConnSMS[$host] + 1 ))

		# "(ComBus) ActiveMQ Exception Listener Called" Log
		elif [[ "$log" =~ \
				ActiveMQ${S}Exception${S}Listener${S}Called ]]; then
			#echo "ActiveMQ Exception Listener Called..."
			nHostDASMONDActiveMQException[$host]=$(( \
				nHostDASMONDActiveMQException[$host] + 1 ))

		# "(ComBus) Error Broadcasting Message" Log
		elif [[ "$log" =~ \
				broadcast\(\):${S}Error${S}Broadcasting${S}Message ]]; then
			#echo "ComBus Error Broadcasting Message..."
			nHostDASMONDComBusBroadcastError[$host]=$(( \
				nHostDASMONDComBusBroadcastError[$host] + 1 ))

		# "ComBus Connection Timeout for Domain" Log
		elif [[ "$log" =~ \
				ComBus${S}Connection${S}Timeout${S}for${S}Domain ]]; then
			#echo "ComBus Connection Timeout for Domain..."
			nHostDASMONDComBusConnTimeout[$host]=$(( \
				nHostDASMONDComBusConnTimeout[$host] + 1 ))

		# "(ComBus) Error Disconnecting Message Producers/Consumers" Log
		elif [[ "$log" =~ \
			Error${S}Disconnecting${S}Message${S}Producers/Consumers ]]; \
		then
			#echo "ComBus Error Disconnecting Message Producers/Consumers"
			nHostDASMONDComBusDisconnectError[$host]=$(( \
				nHostDASMONDComBusDisconnectError[$host] + 1 ))

		# "(ComBus) Reconnect Thread" Logs
		elif [[ "$log" =~ ComBus:${S}reconnectThread\(\) ]]; then
			#echo "ComBus Reconnect Thread..."
			nHostDASMONDComBusReconnectThread[$host]=$(( \
				nHostDASMONDComBusReconnectThread[$host] + 1 ))

		# "OversizePkt" Log
		elif [[ "$log" =~ OversizePkt ]]; then
			#echo "OversizePkt..."
			nHostDASMONDOversizePkt[$host]=$(( \
				nHostDASMONDOversizePkt[$host] + 1 ))

		# Unknown Log Message
		else
			nUnknownDASMOND=$(( nUnknownDASMOND + 1 ))
			known=0
		fi
	fi

	if [[ $known == 0 ]]; then
		#echo "*** Unknown Log Message!"
		nUnknownLogs=$(( nUnknownLogs + 1 ))
		return 1
	else
		return 0
	fi
}

#
# Process Each File in Turn...
#

echo
echo "Processing File List: ${FileList}"
echo

last_hdr_from=""

for f in ${FileList} ; do

	echo "[$f]"

	lastFileFrom[${f}]=""

	while read line ; do

		# Only Process Actual Log Messages...

		# New RHel7-Style Log Message Timestamps...
		if [[ $line =~ ^20[0-9][0-9]- ]]; then

			#echo "Rhel7Log=[$line]"
			nlog=$(( nlog + 1 ))

			# Strip Off Log Timestamp (to align parsing...)
			ts=`echo "$line" | awk '{print $1}'`
			#echo "ts=[$ts]"
			log=`echo "$line" | sed "s/$ts //"`

			PARSE_LOG "$log"
			if [[ $? != 0 ]]; then
				if [[ -n "$last_hdr_from" ]]; then
					echo -e "\n[$f]"
					echo "$last_hdr_from"
					# Only Dump From Header Once Per Email...
					last_hdr_from=""
				fi
				echo "$line"
			fi

		# Old RHel6-Style Log Message Timestamps...
		elif [[ $line =~ ^Jan${S} || $line =~ ^Feb${S} \
			|| $line =~ ^Mar${S} || $line =~ ^Apr${S} \
			|| $line =~ ^May${S} || $line =~ ^Jun${S} \
			|| $line =~ ^Jul${S} || $line =~ ^Aug${S} \
			|| $line =~ ^Sep${S} || $line =~ ^Oct${S} \
			|| $line =~ ^Nov${S} || $line =~ ^Dec${S} \
		]]; then \

			#echo "Rhel6Log=[$line]"
			nlog=$(( nlog + 1 ))

			# Strip Off Log Timestamp (to align parsing...)
			ts=`echo "$line" | awk '{printf "%s %2s %s", $1, $2, $3}'`
			#echo "ts=[$ts]"
			log=`echo "$line" | sed "s/$ts //"`

			PARSE_LOG "$log"
			if [[ $? != 0 ]]; then
				if [[ -n "$last_hdr_from" ]]; then
					echo -e "\n[$f]"
					echo "$last_hdr_from"
					# Only Dump From Header Once Per Email...
					last_hdr_from=""
				fi
				echo "$line"
			fi

		# Blank Lines...
		elif [[ $line =~ ^$ ]]; then
			#echo "BlankLine=[$line]"
			nblank=$(( nblank + 1 ))

		# Other/Email Header Lines...
		else

			#echo "NonLog=[$line]"
			nhdr=$(( nhdr + 1 ))

			# Capture Each Email "From" Line as we go, for Errors...
			if [[ $line =~ ^From${S} ]]; then
				lastFileFrom[${f}]="$line"
				last_hdr_from="$line"
				nemail=$(( nemail + 1 ))
			fi

		fi

	done < "$f"

done

#
# Done, Dump Statistics...
#

echo -e "\n--- Statistics Summary ---\n"

echo "Per Host Statistics:"
for h in ${HostList} ; do
	echo -e "\nHost [$h] - ${nHostlogs[$h]} Logs Total"
	if [[ ${nHostSTSVarValueSawtooth[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSVarValueSawtooth[$h]} "
		echo "STS \"Variable Value Update SAWTOOTH\" Logs"
	fi
	if [[ ${nHostSTSVarValueTruncateNegTime[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSVarValueTruncateNegTime[$h]} "
		echo "STS \"Truncate Negative Variable Value Update Time\" Logs"
	fi
	if [[ ${nHostSTSMoreThanOnePVValue[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSMoreThanOnePVValue[$h]} "
		echo "STS \"More Than 1 PV Value for\" Logs"
	fi
	if [[ ${nHostSTSNoMatchingUnitsPV[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSNoMatchingUnitsPV[$h]} "
		echo "STS \"No Matching Units PV Found\" Logs"
	fi
	if [[ ${nHostSTSLdapLookupUserName[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSLdapLookupUserName[$h]} "
		echo "STS \"LDAP Lookup User Name\" Logs"
	fi
	if [[ ${nHostSTSActiveMQException[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSTSActiveMQException[$h]} "
		echo "STS \"ActiveMQ Exception Listener Called\" Logs"
	fi
	if [[ ${nHostSTSComBusBroadcastError[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSTSComBusBroadcastError[$h]} "
		echo "STS \"ComBus Error Broadcasting Message\" Logs"
	fi
	if [[ ${nHostSTSComBusConnTimeout[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSComBusConnTimeout[$h]} "
		echo "STS \"ComBus Connection Timeout for Domain\" Logs"
	fi
	if [[ ${nHostSTSComBusDisconnectError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSComBusDisconnectError[$h]} "
		echo "STS \"ComBus Error Disconnecting Producers/Consumers\" Logs"
	fi
	if [[ ${nHostSTSComBusReconnectThread[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSComBusReconnectThread[$h]} "
		echo "STS \"ComBus Reconnect Thread\" Logs"
	fi
	if [[ ${nHostSTSUpdatingRunInfo[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSUpdatingRunInfo[$h]} "
		echo "STS \"Updating RunInfo\" Logs"
	fi
	if [[ ${nHostSTSDetBankSetConfigErr[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSDetBankSetConfigErr[$h]} "
		echo "STS \"Detector Bank Set Config Error\" Logs"
	fi
	if [[ ${nHostSTSDetBankSetRestrictEv[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSTSDetBankSetRestrictEv[$h]} "
		echo "STS \"Restricting Detector Bank Set to Event Mode\" Logs"
	fi
	if [[ ${nHostSTSDuplicatePulse[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSTSDuplicatePulse[$h]} "
		echo "STS \"Duplicate Pulse\" Logs"
	fi
	if [[ ${nHostSTSOversizePkt[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSTSOversizePkt[$h]} "
		echo "STS \"OversizePkt\" Logs"
	fi
	if [[ ${nHostSMSDRunAwayDataSource[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSMSDRunAwayDataSource[$h]} "
		echo "SMSD \"Run-Away Data Source\" Logs"
	fi
	if [[ ${nHostSMSDMissingRingPeriod[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSMSDMissingRingPeriod[$h]} "
		echo "SMSD \"Missing ring period\" Logs"
	fi
	if [[ ${nHostSMSDSystemNOTReady[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDSystemNOTReady[$h]} "
		echo "SMSD \"System NOT Ready\" Logs"
	fi
	if [[ ${nHostSMSDSystemReady[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDSystemReady[$h]} "
		echo "SMSD \"System Ready\" Logs"
	fi
	if [[ ${nHostSMSDDataSourceTimedOut[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSMSDDataSourceTimedOut[$h]} "
		echo "SMSD \"Timed out waiting for data (Past Retry!)\" Logs"
	fi
	if [[ ${nHostSMSDDataSourceTimedOutRetry[$h]} -gt 0 ]]; then
		echo -n "   * ${nHostSMSDDataSourceTimedOutRetry[$h]} "
		echo "SMSD \"Timed out waiting for data (Retry)\" Logs"
	fi
	if [[ ${nHostSMSDNoRTDLForPulse[$h]} -gt 0 ]]; then
		echo -n "   * ${nHostSMSDNoRTDLForPulse[$h]} "
		echo "SMSD \"NO RTDL for Pulse\" Logs"
	fi
	if [[ ${nHostSMSDNoMorePulsesForCorrect[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDNoMorePulsesForCorrect[$h]} "
		echo "SMSD \"No More Pulses for PCharge/Veto Correction\" Logs"
	fi
	if [[ ${nHostSMSDCorrectPChargeVeto[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDCorrectPChargeVeto[$h]} "
		echo "SMSD \"correctPChargeVeto\" Logs"
	fi
	if [[ ${nHostSMSDLocalSAWTOOTHRTDL[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSMSDLocalSAWTOOTHRTDL[$h]} "
		echo "SMSD \"Local SAWTOOTH RTDL\" Logs"
	fi
	if [[ ${nHostSMSDLocalSAWTOOTHData[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSMSDLocalSAWTOOTHData[$h]} "
		echo "SMSD \"Local SAWTOOTH RawData\" Logs"
	fi
	if [[ ${nHostSMSDGlobalSAWTOOTH[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDGlobalSAWTOOTH[$h]} "
		echo "SMSD \"Global SAWTOOTH Pulse\" Logs"
	fi
	if [[ ${nHostSMSDPulseNoRegEvent[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDPulseNoRegEvent[$h]} "
		echo "SMSD \"Pulse with No Registered Event Sources\" Logs"
	fi
	if [[ ${nHostSMSDFirstNewEventSource[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDFirstNewEventSource[$h]} "
		echo "SMSD \"First New Event Source Registered\" Logs"
	fi
	if [[ ${nHostSMSDLastEventSource[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDLastEventSource[$h]} "
		echo "SMSD \"Last Event Source Unregistered\" Logs"
	fi
	if [[ ${nHostSMSDLiveClientLogs[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDLiveClientLogs[$h]} "
		echo "SMSD \"Live Client\" Logs"
	fi
	if [[ ${nHostSMSDActiveMQException[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDActiveMQException[$h]} "
		echo "SMSD \"ActiveMQ Exception Listener Called\" Logs"
	fi
	if [[ ${nHostSMSDComBusBroadcastError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDComBusBroadcastError[$h]} "
		echo "SMSD \"ComBus Error Broadcasting Message\" Logs"
	fi
	if [[ ${nHostSMSDComBusConnTimeout[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDComBusConnTimeout[$h]} "
		echo "SMSD \"ComBus Connection Timeout for Domain\" Logs"
	fi
	if [[ ${nHostSMSDComBusDisconnectError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDComBusDisconnectError[$h]} "
		echo "SMSD \"ComBus Error Disconnecting Producers/Consumers\" Logs"
	fi
	if [[ ${nHostSMSDComBusReconnectThread[$h]} -gt 0 ]]; then
		echo -n "   ${nHostSMSDComBusReconnectThread[$h]} "
		echo "SMSD \"ComBus Reconnect Thread\" Logs"
	fi
	if [[ ${nHostSMSDOversizePkt[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostSMSDOversizePkt[$h]} "
		echo "SMSD \"OversizePkt\" Logs"
	fi
	if [[ ${nHostPVSDINITHUNG[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostPVSDINITHUNG[$h]} "
		echo "PVSD \"INIT HUNG\" Logs"
	fi
	if [[ ${nHostPVSDDeviceRecoveredFromHung[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostPVSDDeviceRecoveredFromHung[$h]} "
		echo "PVSD \"Device has recovered from hung state\" Logs"
	fi
	if [[ ${nHostPVSDEPICSCAException[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostPVSDEPICSCAException[$h]} "
		echo "PVSD \"Caught EPICS CA Exception\" Logs"
	fi
	if [[ ${nHostPVSDActiveMQException[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDActiveMQException[$h]} "
		echo "PVSD \"ActiveMQ Exception Listener Called\" Logs"
	fi
	if [[ ${nHostPVSDComBusBroadcastError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDComBusBroadcastError[$h]} "
		echo "PVSD \"ComBus Error Broadcasting Message\" Logs"
	fi
	if [[ ${nHostPVSDComBusConnTimeout[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDComBusConnTimeout[$h]} "
		echo "PVSD \"ComBus Connection Timeout for Domain\" Logs"
	fi
	if [[ ${nHostPVSDComBusDisconnectError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDComBusDisconnectError[$h]} "
		echo "PVSD \"ComBus Error Disconnecting Producers/Consumers\" Logs"
	fi
	if [[ ${nHostPVSDComBusReconnectThread[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDComBusReconnectThread[$h]} "
		echo "PVSD \"ComBus Reconnect Thread\" Logs"
	fi
	if [[ ${nHostPVSDDefiningNewDevice[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDDefiningNewDevice[$h]} "
		echo "PVSD \"Defining New Device\" Logs"
	fi
	if [[ ${nHostPVSDUndefineDevice[$h]} -gt 0 ]]; then
		echo -n "   * ${nHostPVSDUndefineDevice[$h]} "
		echo "PVSD \"Undefine Device\" Logs"
	fi
	if [[ ${nHostPVSDUndefineDevicePkt[$h]} -gt 0 ]]; then
		echo -n "   * ${nHostPVSDUndefineDevicePkt[$h]} "
		echo "PVSD \"Sending Empty Descriptor to *Undefine* Device\" Logs"
	fi
	if [[ ${nHostPVSDMakePvNamesUnique[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostPVSDMakePvNamesUnique[$h]} "
		echo "PVSD \"Make PV Names Unique (Name Clash!)\" Logs"
	fi
	if [[ ${nHostPVSDAssignPVID[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDAssignPVID[$h]} "
		echo "PVSD \"Assign PV ID\" Logs"
	fi
	if [[ ${nHostPVSDInactiveDeviceID[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDInactiveDeviceID[$h]} "
		echo "PVSD \"Inactive Device ID\" Logs"
	fi
	if [[ ${nHostPVSDDeviceNotYetDefined[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDDeviceNotYetDefined[$h]} "
		echo "PVSD \"Device Not Yet Defined\" Logs"
	fi
	if [[ ${nHostPVSDSubscriptionCreated[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDSubscriptionCreated[$h]} "
		echo "PVSD \"Subscription Created\" Logs"
	fi
	if [[ ${nHostPVSDClearingSubscription[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDClearingSubscription[$h]} "
		echo "PVSD \"Clearing Subscription\" Logs"
	fi
	if [[ ${nHostPVSDConnectedToSMSClient[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDConnectedToSMSClient[$h]} "
		echo "PVSD \"Connected to ADARA SMS Client\" Logs"
	fi
	if [[ ${nHostPVSDInitialSendsComplete[$h]} -gt 0 ]]; then
		echo -n "   ${nHostPVSDInitialSendsComplete[$h]} "
		echo "PVSD \"Initial Sends Complete to ADARA SMS\" Logs"
	fi
	if [[ ${nHostPVSDAlive[$h]} -gt 0 ]]; then
		echo "   ${nHostPVSDAlive[$h]} \"PVSD is Alive\" Logs"
		if [[ ${nHostPVSDPartial[$h]} -gt 0 ]]; then
			avgp=$(( ${nHostPVSDPartial[$h]} / ${nHostPVSDAlive[$h]} ))
			echo -n "   *** $avgp Avg Partial Devices "
			echo "(${nHostPVSDPartial[$h]} Total)"
		fi
		if [[ ${nHostPVSDHung[$h]} -gt 0 ]]; then
			avgh=$(( ${nHostPVSDHung[$h]} / ${nHostPVSDAlive[$h]} ))
			echo -n "   *** $avgh Avg Hung Devices "
			echo "(${nHostPVSDHung[$h]} Total)"
		fi
	fi
	if [[ ${nHostPVSDOversizePkt[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostPVSDOversizePkt[$h]} "
		echo "PVSD \"OversizePkt\" Logs"
	fi
	if [[ ${nHostDASMONDFailedToConnSMS[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostDASMONDFailedToConnSMS[$h]} "
		echo "DASMOND \"Failed to Connect to SMS\" Logs"
	fi
	if [[ ${nHostDASMONDActiveMQException[$h]} -gt 0 ]]; then
		echo -n "   ${nHostDASMONDActiveMQException[$h]} "
		echo "DASMOND \"ActiveMQ Exception Listener Called\" Logs"
	fi
	if [[ ${nHostDASMONDComBusBroadcastError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostDASMONDComBusBroadcastError[$h]} "
		echo "DASMOND \"ComBus Error Broadcasting Message\" Logs"
	fi
	if [[ ${nHostDASMONDComBusConnTimeout[$h]} -gt 0 ]]; then
		echo -n "   ${nHostDASMONDComBusConnTimeout[$h]} "
		echo "DASMOND \"ComBus Connection Timeout for Domain\" Logs"
	fi
	if [[ ${nHostDASMONDComBusDisconnectError[$h]} -gt 0 ]]; then
		echo -n "   ${nHostDASMONDComBusDisconnectError[$h]} "
		echo \
		  "DASMOND \"ComBus Error Disconnecting Producers/Consumers\" Logs"
	fi
	if [[ ${nHostDASMONDComBusReconnectThread[$h]} -gt 0 ]]; then
		echo -n "   ${nHostDASMONDComBusReconnectThread[$h]} "
		echo "DASMOND \"ComBus Reconnect Thread\" Logs"
	fi
	if [[ ${nHostDASMONDOversizePkt[$h]} -gt 0 ]]; then
		echo -n "   *** ${nHostDASMONDOversizePkt[$h]} "
		echo "DASMOND \"OversizePkt\" Logs"
	fi
done
echo

echo "Per App Statistics:"
if [[ $nSTS -gt 0 ]]; then
	echo "$nSTS STS Logs"
fi
if [[ $nSMSD -gt 0 ]]; then
	echo "$nSMSD SMSD Logs"
fi
if [[ $nPVSD -gt 0 ]]; then
	echo "$nPVSD PVSD Logs"
fi
if [[ $nDASMOND -gt 0 ]]; then
	echo "$nDASMOND DASMOND Logs"
fi
echo

echo "Unknown Log/Error Messages: $nUnknownLogs"
if [[ $nUnknownSTS -gt 0 ]]; then
	echo "$nUnknownSTS Unknown STS Logs"
fi
if [[ $nUnknownSMSD -gt 0 ]]; then
	echo "$nUnknownSMSD Unknown SMSD Logs"
fi
if [[ $nUnknownPVSD -gt 0 ]]; then
	echo "$nUnknownPVSD Unknown PVSD Logs"
fi
if [[ $nUnknownDASMOND -gt 0 ]]; then
	echo "$nUnknownDASMOND Unknown DASMOND Logs"
fi
echo

echo "General Statistics:"
echo "$nemail Emails Found"
echo "$nlog Lines of Log Input"
echo "$nhdr Lines of Non-Log Header Input"
echo "$nblank Blank Lines of Input"
echo

echo "Last Email Per File:"
for f in ${FileList} ; do
	if [[ -n "${lastFileFrom[$f]}" ]]; then
		echo -e "[$f]:\n   ${lastFileFrom[$f]}"
	fi
done
echo

