#!/bin/bash
#
# ADARA Monitor
#
# Periodically Process & Display Summary Statistics for
# Extracted ADARA "Critical ADARA Syslog Error" Log Messages.
#

ADARA_SUMMARY="$HOME/gitsrc/ADARA/adara_summary"

CACHE_DIR="/SNSlocal/rsyslog.cache"

ALTOPT="" # for Alternate/Secondary SMS Deployments... ;-D

#
# Dump Usage
#

USAGE()
{
	echo
	echo "usage:  adara_monitor [--alt=\"-mon\"] \\"
	echo "                      [--adara_summary=<path>] \\"
	echo "                      [--cache_dir=<CACHE_DIR>] [--help|-h]"
	echo

	echo "where:"
	echo

	echo "    --alt=\"-mon\"          = run for Alternate SMS Suffix"
	echo
	echo " --adara_summary=<path>   = path to ADARA Summary script"
	echo "                            [${ADARA_SUMMARY}]"
	echo
	echo " --cache_dir=<CACHE_DIR>  = location of local error cache files"
	echo "                            [${CACHE_DIR}]"
	echo
	echo "     --help | -h          = display this usage information"
	echo
}

for arg in "$@" ; do
	# echo "arg=$arg"
	key=`echo "$arg" | awk -F = '{print $1}'`
	value=`echo "$arg" | awk -F = '{print $2}'`
	# echo "key=$key"
	# echo "value=$value"
	if [[ "#$key#" == '#-h#' || "#$key#" == '#--help#' ]]; then
		USAGE
		exit 0
	elif [[ "#$key#" == '#--alt#' ]]; then
		ALTOPT="--alt=$value"
		echo -e "\nUsing Alternate SMS Suffix: --alt=\"${value}\""
	elif [[ "#$key#" == '#--adara_summary#' ]]; then
		if [ -x "$value" ]; then
			ADARA_SUMMARY="$value"
			echo -e "\nUsing ADARA Summary Script in:\n\t[${CACHE_DIR}]"
		else
			echo -e "\nError: ADARA Summary Script Not Found/Executable!"
			echo -e "\t[$value]"
			/bin/ls -l "$value"
			USAGE
			exit -3
		fi
	elif [[ "#$key#" == '#--cache_dir#' ]]; then
		if [ -d "$value" ]; then
			CACHE_DIR="$value"
			echo -e "\nUsing Syslog Error Cache in:\n\t[${CACHE_DIR}]"
		else
			echo -e "\nError: Cache Directory Not Found!\n\t[$value]"
			/bin/ls -l "$value"
			USAGE
			exit -2
		fi
	else
		echo -e "\nError: Unknown Option/Unrecognized File:\n [${key}]"
		USAGE
		exit -1
	fi
done

# Make Sure ADARA Summary is Present and Executable...
if [[ ! -x ${ADARA_SUMMARY} ]]; then
	echo -e "\nError: ADARA Summary Script Not Found/Executable!"
	echo -e "\t[${ADARA_SUMMARY}]"
	/bin/ls -l "${ADARA_SUMMARY}"
	USAGE
	exit -4
fi

#
# Set Up ADARA Monitor Summary Log & Previous Summary Marker File...
#

SUMMARY="AdaraMonitorSummary.$$.log"

PREVIOUS="AdaraMonitorPreviousMarker.$$.marker"

##
## Functions:
##

#
# Generate an ADARA Summary File...
#

DO_SUMMARY()
{
	echo

	echo -n "Starting Summary: "
	date

	/bin/rm "${CACHE_DIR}/${SUMMARY}" > /dev/null 2>&1

	# Remove Globbed File List If None Found...
	shopt -s nullglob

	${ADARA_SUMMARY} --terse --nostdin ${ALTOPT} "${CACHE_DIR}"/*.txt \
		> "${CACHE_DIR}/${SUMMARY}"

	# Restore Normal Shell Globbing...
	shopt -u nullglob

	LAST_CACHE_STATE=`/bin/ls -ld "${CACHE_DIR}"`

	/bin/cat "${CACHE_DIR}/${SUMMARY}"

	LAST_TIME=`date +"%s"`

	# Check for Intervening User Input, Which Should Probably Be Ignored
	# (Especially a "Clear Cache" Command, which probably referred to
	# the Results of the _Previous_ ADARA Summary Output...! ;-D)
	# (Now there's a new "Clear Previous" Command for that! ;-D)

	local _cmd=""

	while [[ true ]]; do

		# Check for Input Already Waiting
		# (Timeout = 0.1, as 0 works weirdly...)
		IFS= read -t 0.1 -n 1 -s _cmd

		# Got a Command, Optionally Ignore It...!
		if [[ $? == 0 ]]; then
			DO_CMD "${_cmd}" IGNORE
		else
			break
		fi
	
	done

	# Leave "Previous" Breadcrumb for Next ADARA Summary... ;-D
	touch "${CACHE_DIR}/${PREVIOUS}"

	echo -n "Summary Done: "
	date
}

#
# Clear Local Cache Directory...
#

CLEAR_CACHE()
{
	echo -e -n "\nRemoving Any Processed Local Cache Files "
	echo -e "or Leftover Summaries:\n"

	# Remove Any Older Files than the Current ADARA Summary File...
	find "${CACHE_DIR}/" \
		-mindepth 1 -not -cnewer "${CACHE_DIR}/${SUMMARY}" \
		-and -not -path "${CACHE_DIR}/${SUMMARY}" \
		-print -exec /bin/rm -f {} \;

	# Generate a New ADARA Summary Now...
	echo -e "\nRefreshing ADARA Summary..."
	DO_SUMMARY
}

#
# Clear Previous Local Cache Directory...
#

CLEAR_PREVIOUS_CACHE()
{
	if [[ ! -f "${CACHE_DIR}/${PREVIOUS}" ]]; then
		echo -e "\nNo Previous ADARA Summary Marker File Found..."
		echo "Ignoring Command."
		return
	fi

	echo -e -n "\nRemoving Any Previously Processed Local Cache Files "
	echo -e "or Leftover Summaries:\n"

	# Remove Any Older Files than the Previous ADARA Summary Marker File...
	find "${CACHE_DIR}/" \
		-mindepth 1 -not -cnewer "${CACHE_DIR}/${PREVIOUS}" \
		-and -not -path "${CACHE_DIR}/${PREVIOUS}" \
		-print -exec /bin/rm -f {} \;

	# Generate a New ADARA Summary Now...
	echo -e "\nRefreshing ADARA Summary..."
	DO_SUMMARY
}

#
# Dump Interactive Command Usage...
#

CMD_USAGE()
{
	echo -e "\nADARA Monitor Interactive Command Usage:\n"

	echo -e "<space> or <tab>  = Refresh the Latest ADARA Summary\n"
	echo -e "     C or c       = Clear Current Local Syslog Error Cache\n"
	echo -e "     P or p       = Clear Previous Local Syslog Error Cache\n"
	echo -e "     Q or q       = Quit ADARA Monitor\n"
	echo -e "   H or h or ?    = Display this Interactive Command Usage\n"
}

#
# Interpret and Execute Interactive Commands...
#

DO_CMD()
{
	local _cmd="$1"
	shift

	local _ignore="$1"
	shift

	local _ignored=0

	local _nl="\n"
	if [[ ${_ignore} == "IGNORE" ]]; then _nl="" ; fi

	if [[ "${_cmd}" == "Q" || "${_cmd}" == "q" ]]; then
		echo -e "${_nl}Exiting ADARA Monitor at User's Request.\n"
		exit 0
	elif [[ "${_cmd}" == " " || "${_cmd}" == "	" ]]; then
		if [[ ${_ignore} == "IGNORE" ]]; then
			_ignored=1
		else
			echo -e "${_nl}Refreshing ADARA Summary..."
			DO_SUMMARY
		fi
	elif [[ "${_cmd}" == "C" || "${_cmd}" == "c" ]]; then
		if [[ ${_ignore} == "IGNORE" ]]; then
			_ignored=1
		else
			echo -e "${_nl}Clearing ADARA Summary Statistics..."
			CLEAR_CACHE
		fi
	elif [[ "${_cmd}" == "P" || "${_cmd}" == "p" ]]; then
		echo -e "${_nl}Clearing Previous ADARA Summary Statistics..."
		CLEAR_PREVIOUS_CACHE
		if [[ ${_ignore} == "IGNORE" ]]; then echo ; fi
	elif [[ "${_cmd}" == "H" || "${_cmd}" == "h" \
			|| "${_cmd}" == "?" ]]; then
		CMD_USAGE
	# Ignore Carriage Returns... ;-D
	elif [[ "${_cmd}" != "" ]]; then
		CMD_USAGE
		echo "Error: Unknown Interactive Command [${_cmd}]...!"
		if [[ ${_ignore} == "IGNORE" ]]; then echo ; fi
	fi

	# Log Any Ignored Commands...
	if [[ ${_ignored} == 1 ]]; then
		echo -e -n "${_nl}Warning: User Input Received "
		echo "During ADARA Summary Update!"
		echo "Ignoring User Command(s) [${_cmd}]..."
		echo
	fi
}

##
## End of Functions.
##

#
# Generate Initial ADARA Summary...
#

LAST_CACHE_STATE=""
LAST_TIME=0

DO_SUMMARY

#
# Main Interactive Loop
#

while [[ true ]]; do

	# Check for Interactive Command Input...
	IFS= read -t 10 -n 1 -s cmd

	# Got a Command, Execute It...
	if [[ $? == 0 ]]; then
		DO_CMD "$cmd"
	fi

	#
	# Check for Changes to Local Cache Directory...
	#

	cache_state=`/bin/ls -ld "${CACHE_DIR}"`

	if [[ "${cache_state}" != "${LAST_CACHE_STATE}" ]]; then
		echo -e "\nLocal Cache Directory Changed, Refreshing ADARA Summary."
		DO_SUMMARY
	fi

	#
	# Calculate Elapsed Time Since Last ADARA Summary...
	#

	now=`date +"%s"`

	elapsed=$(( now - LAST_TIME ))

	if [[ $elapsed -gt 180 ]]; then
		echo -e "\nAuto-Refreshing Latest ADARA Summary."
		DO_SUMMARY
	fi

done

