# Critical ADARA SMS Messages - Email Notification
   :msg, contains, "ERROR SMS"          |/etc/rsyslog.pipes/criticalMessages
   :msg, contains, "PVSD ERROR"         |/etc/rsyslog.pipes/criticalMessages
   :msg, contains, "STC Error"          |/etc/rsyslog.pipes/criticalMessages
   :msg, contains, "STC failed"         |/etc/rsyslog.pipes/criticalMessages
   :msg, contains, "Unexpected input"   |/etc/rsyslog.pipes/criticalMessages
   :msg, contains, "OversizePkt"        |/etc/rsyslog.pipes/criticalMessages
