[sms]
	# Let SMS know where to find everything
	#
	basedir = /SNSlocal/sms

[storage]
	# The data pool base directory can be moved, but defaults to
	# the global $BASEDIR/data.
	#
	# basedir = /SNSlocal/sms/data

	# Poolsize will take precendence over percentage
	poolsize = 4G
	percent = 50

	# filesize controls how large individual files can grow
	#
	filesize = 200M

	# syncdist indicates how often we'll insert a sync packet
	#
	syncdist = 16M

[stsclient]
	# What address should we use to connect to the STS?
	#
	# uri = localhost:31417

	# How many simultaneous connections to STS do we allow?
	# This should be sized relative to the number of machines in the
	# STS cluster, allowing for fairness between beam lines.
	#
	# max_connections = 3

	# How many seconds do we wait for our connection attempt to succeed?
	# We assume a fast, local network by default.
	#
	# connect_timeout = 15.0

	# After a failed connection attempt, how long do we wait to retry?
	#
	# reconnect_timeout = 15.0

	# If STS just goes away without sending a translation complete
	# packet, how long do we wait to retry?
	#
	# transient_timeout = 60.0

	# How many seconds do we let the the connection idle before we
	# send a heartbeat packet
	#
	# heartbeat = 5.0

	# Maximum data chunk to pass to sendfile() -- larger is more
	# efficient, but too large starves operations as we block in the
	# call.
	#
	# maxsend = 2M
