[sms]
	# Let SMS know where to find everything
	#
	basedir = /SNSlocal/sms

[storage]
	# The data pool base directory can be moved, but defaults to
	# the global $BASEDIR/data.
	#
	# basedir = /SNSlocal/sms/data

	# Poolsize will take precendence over percentage
	poolsize = 4G
	percent = 50

	# filesize controls how large individual files can grow
	#
	filesize = 200M

	# syncdist indicates how often we'll insert a sync packet
	#
	syncdist = 16M
