#!/bin/bash
#
# STC View Script
#
# Search STC Log Entries to Track the Progress of a Specific STC Process ID
#

num_files=5

do_run=0

if [[ "$1" == "--run" ]]; then
	do_run=1
	shift
fi

if [[ $# < 1 ]]; then
	echo "usage: stcview [--run] <pid/run>"
	exit -1
fi

if [[ $do_run == 1 ]]; then
	run="$1"
	pid=`stcrun --pid $run | tail -1`
	if [[ -z "$pid" ]]; then
		echo -e "\nRun Number ${run} Not Found on This Server.\n"
		exit -1
	else
		echo -e "\nResolved Run Number ${run} as Process Id ${pid}.\n"
	fi
else
	pid="$1"
fi

# Search Log Files
log_lines=`stc_search_logs --num_files=${num_files} ${pid}`

# Determine Whether Pager Required...

nlines=`echo "$log_lines" | wc | awk '{print $1}'`

if [[ $nlines -gt 48 ]]; then

	echo "${log_lines}" | /usr/bin/less -x4 +"G?Target Station"

else

	echo "${log_lines}"

fi

