.TH sts 1 "October 2012" "version 0.1.1"
.SH NAME
sts - ADARA streaming translation service
.SH SYNOPSIS
sts [OPTION]
.SH DESCRIPTION
The sts is a stream translation process used to create Nexus files within the
SNS ADARA data acquisition and analysis system. The sts process is typically
installed as an xinetd service that is started in respone to a request by the
stream management service (sms) process; however, sts can be run from the
command line to manually translate or inspect ADARA streams. There are two
methods of manually translating an ADARA stream file: piping a file to sts,
or using the --file (-f) option to specify an input file. For example, the
following two commands are equivalent:
.IP "cat streaamfile.adara | ./sts"
.IP "./sts -f streamfile.adara"
.PP
When run without options, sts generates an uncompressed Nexus output file
and an ADARA output file in the current working directory using a temporary
file-naming scheme. If the --move option is specified, these files are moved
to their respective cataloging locations and renamed to conform to SNS
cataloging service requirements. (Note: for the move to succeed, the working
directory and the catalogging directories must reside in the same physical
storage device.)
.PP
To use the sts as a simple stream statisics tool, enable statistics reporting
and disable both nexus file and ADARA file generation, as follows:

.IP "sts -n -a -r"

.SH OPTIONS
.IP "-h, --help"
Displays usage text and exits.
.IP "--version"
Displays sts version number and exits.
.IP "-i, --interactive"
Enables "interactive" mode (displays information to console)
.IP "-v, --verbose"
Enables verbose output (requires interactive mode)
.IP "-s, --strict"
Enables strict processing of ADARA protocol (i.e. checks required fields)
.IP "-m, --move"
Enables moving of output file(s) to cataloging path (strict processing is
automatically enabled if move option is enabled). The working directory and
the cataloging directoies must reside on the same physical storage device, or
the move will fail. The cataloging path is defined as /Facility/Instrument/ProposalId.
.IP "-r, --report"
Gathers and displays ADARA stream statistics (requires interactive option)
.IP "-n, --no-nexus"
Disables generation of Nexus output file (--strict overrides this option).
.IP "-a, --no-adara"
Disables generation of ADARA output file (--strict overrides this option).
.IP "-f, --file filename"
Specifies an input ADARA file to read instead of stdin.
.IP "-w, --work-path"
Specifies working directory where Nexus and ADARA files are written. If --move
option is enabled, the working directory must reside on the same physical
storage device.
.IP "-c, --compression-level"
Specifies HDF5 compression level for Nexus output (0 = none, 9 = maximum).
Compression increases memory use and reduces stream translation speed.
.IP "--chunk-size"
Sets the HDF5 file chunk size, in bytes.
.IP "--cache-size"
Sets the HDF5 cache size (important when compression is enabled).
.IP "--event-buf-size"
Sets neutron event buffer size, in chunks.
.IP "--anc-buf-size"
Sets ancillary buffer size, in chunks. Ancillary buffers are used for process
variables, pulse metadata, and other non-nuetron data.

