#!/bin/bash

#
# Production-Deployed STS Configuration Files
#    - on sns-sts1.sns.gov
#    - on sns-sts2.sns.gov
#

STS_DIR="/SNS/users/y8y"

STS_SSH="ssh -AY sns-sts1.sns.gov"
#STS_SSH="ssh -AY sns-sts2.sns.gov"

STS_PROD="/SNS/lustre/stsdata/sts_config.xml"
STS_TEST="/SNS/lustre/stsdata_test/sts_config.xml"
STS_DUMMY="/TESTING/SNS/stsdata_dummy/sts_config.xml"
STS_HFIR="/HFIR/stsdata_hfir/sts_config.xml"
STS_HFIR_TEST="/HFIR/stsdata_hfir_test/sts_config.xml"
STS_DEVEL="/TESTING/SNS/stsdata_devel/sts_config.xml"
STS_MASTER="/TESTING/SNS/stsdata_master/sts_config.xml"
STS_TESTING="/TESTING/SNS/stsdata/sts_config.xml"
STS_JENKINS="/TESTING/JENKINS/SNS/stsdata/sts_config.xml"
STS_JENKINS_DEVEL="/TESTING/JENKINS/SNS/stsdata_devel/sts_config.xml"

USAGE()
{
	echo -e "\nusage: updateConfig [--diff] \\"
	echo "   [ --prod | --test | --dummy | \\"
	echo "      --hfir | --hfir-test | \\"
	echo "      --devel | --master | --testing | \\"
	echo "      --jenkins | --jenkins-devel | --all ]"
	echo
	echo "where:"
	echo
	echo " --diff           = don't actually update STS Configs, Diff Only"
	echo
	echo " --prod           = update Production STS Config"
	echo " --test           = update Production TEST STS Config"
	echo " --dummy          = update Production DUMMY STS Config"
	echo " --hfir           = update Production HFIR STS Config"
	echo " --hfir-test      = update Production HFIR TEST STS Config"
	echo " --devel          = update ADARA Test Harness Devel STS Config"
	echo " --master         = update ADARA Test Harness Master STS Config"
	echo " --testing        = update ADARA Test Harness Generic STS Config"
	echo " --jenkins        = update Jenkins Testing Master STS Config"
	echo " --jenkins-devel  = update Jenkins Testing Devel STS Config"
	echo
}

if [[ $# < 1 ]]; then
	USAGE
	exit -1
fi

CONFIGS=""

DIFFONLY=0

for opt in $@ ; do

	if [[ $opt == "--all" && $DIFFONLY == 0 ]]; then
		echo -e "\nAre you _Sure_ you want to Update 'All' STS Configs...?"
		echo -e "\nThis could Break Production and/or Master Jenkins Tests!"
		echo -en "\nContinue Updating Configs (yes/No/quit)? "

		read cont_ck
		cont_ck=`echo "$cont_ck" | tr '[:upper:]' '[:lower:]'`

		if [[ "#$cont_ck#" == '#y#' || "#$cont_ck#" == '#yes#' ]]; then
			echo -e "\nOk, Continuing to Deploy All STS Config Scripts...\n"
		else 
			echo -e "\nExiting Update Config Script at User's Request.\n"
			exit 0
		fi
	fi

	found=0

	if [[ $opt == "--diff" ]]; then
		DIFFONLY=1
		found=1
	fi

	if [[ $opt == "--prod" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS PROD=$STS_PROD"
		found=1
	fi
	if [[ $opt == "--test" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS TEST=$STS_TEST"
		found=1
	fi
	if [[ $opt == "--dummy" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS DUMMY=$STS_DUMMY"
		found=1
	fi
	if [[ $opt == "--hfir" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS HFIR=$STS_HFIR"
		found=1
	fi
	if [[ $opt == "--hfir-test" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS HFIR-TEST=$STS_HFIR_TEST"
		found=1
	fi
	if [[ $opt == "--devel" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS DEVEL=$STS_DEVEL"
		found=1
	fi
	if [[ $opt == "--master" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS MASTER=$STS_MASTER"
		found=1
	fi
	if [[ $opt == "--testing" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS TESTING=$STS_TESTING"
		found=1
	fi
	if [[ $opt == "--jenkins" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS JENKINS=$STS_JENKINS"
		found=1
	fi
	if [[ $opt == "--jenkins-devel" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS JENKINS-DEVEL=$STS_JENKINS_DEVEL"
		found=1
	fi

	if [[ $found == 0 ]]; then
		echo -e "\nError: Unknown Option \"$opt\"... Bailing out..."
		USAGE
		exit -2
	fi

done

echo -e "\nProcessing STS Configs in:"
echo "$CONFIGS" | sed "s/ /\n/g"

config_temp="$STS_DIR/sts_config_update-$$.xml"
echo -e "\nUsing Temporary STS Config File as:\n\t$config_temp\n"

for config in $CONFIGS ; do

	label=`echo "$config" | awk -F '=' '{print $1}'`
	path=`echo "$config" | awk -F '=' '{print $2}'`

	if [[ $DIFFONLY == 1 ]]; then

		echo -e "Comparing to $label STS Config in:\n\n\t$path\n"

		( echo -e "\n$path\n" ; diff ./sts_config.xml "$path" ; echo ) \
			| less -x4

		echo

		continue

	fi

	echo -e "Updating $label STS Config in:\n\n\t$path\n"

	cp "$path" $config_temp

	xxdiff --title2 "[For ${label}: ${path}]" ./sts_config.xml $config_temp

	# Check for File Differences...
	diff $config_temp "$path" > /dev/null 2>&1
	ckdiff=$?

	if [[ $ckdiff != 0 ]]; then

		diff $config_temp "$path" | less -x4

		echo -en "Deploy Updated Config to:\n\n\t$path\n\n(yes/No/quit)? "

		read deploy_ck
		deploy_ck=`echo "$deploy_ck" | tr '[:upper:]' '[:lower:]'`

		if [[ "#$deploy_ck#" == '#y#' || "#$deploy_ck#" == '#yes#' ]]; then
			$STS_SSH cp $config_temp "$path"
		elif [[ "#$deploy_ck#" == '#q#' \
				|| "#$deploy_ck#" == '#quit#' ]]; then
			echo -e "\nExiting Update Config Script at User's Request.\n"
			/bin/rm $config_temp
			exit 0
		else
			echo -e "\nOk, Leaving Deployed STS Config Script As Is...\n"
		fi
	
	else

		echo -e "No Change to Config File:\n\n\t$path\n"

	fi

done

# Clean Up...
if [[ $DIFFONLY == 0 ]]; then
	/bin/rm $config_temp
fi

