#!/bin/bash

#
# Production-Deployed STS Configuration Files
#    - on sns-sts1.sns.gov
#    - on sns-sts2.sns.gov
#

STS_DIR="/SNS/users/y8y"

STS_SSH="ssh -AY sns-sts1.sns.gov"
#STS_SSH="ssh -AY sns-sts2.sns.gov"

STS_PROD="/SNS/lustre/stsdata/sts_config.xml"
STS_TEST="/SNS/lustre/stsdata_test/sts_config.xml"
STS_DUMMY="/TESTING/SNS/stsdata_dummy/sts_config.xml"
STS_DEVEL="/TESTING/SNS/stsdata_devel/sts_config.xml"
STS_MASTER="/TESTING/SNS/stsdata_master/sts_config.xml"
STS_TESTING="/TESTING/SNS/stsdata/sts_config.xml"
STS_JENKINS="/TESTING/JENKINS/SNS/stsdata/sts_config.xml"
STS_JENKINS_DEVEL="/TESTING/JENKINS/SNS/stsdata_devel/sts_config.xml"

USAGE()
{
	echo -e "\nusage: updateConfig \\"
	echo "   [ --prod | --test | --dummy | \\"
	echo "      --devel | --master | --testing | \\"
	echo "      --jenkins | --jenkins-devel | --all ]"
	echo
}

if [[ $# < 1 ]]; then
	USAGE
	exit -1
fi

CONFIGS=""

for opt in $@ ; do

	if [[ $opt == "--all" ]]; then
		echo -e "\nAre you _Sure_ you want to Update 'All' STS Configs...?"
		echo -e "\nThis could Break Production and/or Master Jenkins Tests!"
		echo -en "\nContinue Updating Configs (yes/No/quit)? "

		read cont_ck
		cont_ck=`echo "$cont_ck" | tr '[:upper:]' '[:lower:]'`

		if [[ "#$cont_ck#" == '#y#' || "#$cont_ck#" == '#yes#' ]]; then
			echo -e "\nOk, Continuing to Deploy All STS Config Scripts...\n"
		else 
			echo -e "\nExiting Update Config Script at User's Request.\n"
			exit 0
		fi
	fi

	found=0
	if [[ $opt == "--prod" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS PROD=$STS_PROD"
		found=1
	fi
	if [[ $opt == "--test" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS TEST=$STS_TEST"
		found=1
	fi
	if [[ $opt == "--dummy" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS DUMMY=$STS_DUMMY"
		found=1
	fi
	if [[ $opt == "--devel" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS DEVEL=$STS_DEVEL"
		found=1
	fi
	if [[ $opt == "--master" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS MASTER=$STS_MASTER"
		found=1
	fi
	if [[ $opt == "--testing" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS TESTING=$STS_TESTING"
		found=1
	fi
	if [[ $opt == "--jenkins" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS JENKINS=$STS_JENKINS"
		found=1
	fi
	if [[ $opt == "--jenkins-devel" || $opt == "--all" ]]; then
		CONFIGS="$CONFIGS JENKINS-DEVEL=$STS_JENKINS_DEVEL"
		found=1
	fi

	if [[ $found == 0 ]]; then
		echo -e "\nError: Unknown Option \"$opt\"... Bailing out..."
		USAGE
		exit -2
	fi

done

echo -e "\nProcessing STS Configs in:"
echo "$CONFIGS" | sed "s/ /\n/g"

config_temp="$STS_DIR/sts_config_update-$$.xml"
echo -e "\nUsing Temporary STS Config File as:\n\t$config_temp\n"

for config in $CONFIGS ; do

	echo "Config: [$config]"

	label=`echo "$config" | awk -F '=' '{print $1}'`
	dir=`echo "$config" | awk -F '=' '{print $2}'`
	echo "label=[$label]"
	echo "dir=[$dir]"

	echo -e "Updating $label STS Config in:\n\n\t$dir\n"

	cp $dir $config_temp

	xxdiff --title2 "[For ${label}: ${dir}]" ./sts_config.xml $config_temp

	# Check for File Differences...
	diff $config_temp $dir > /dev/null 2>&1
	ckdiff=$?

	if [[ $ckdiff != 0 ]]; then

		diff $config_temp $dir | less -x4

		echo -en "Deploy Updated Config to:\n\n\t$dir\n\n(yes/No/quit)? "

		read deploy_ck
		deploy_ck=`echo "$deploy_ck" | tr '[:upper:]' '[:lower:]'`

		if [[ "#$deploy_ck#" == '#y#' || "#$deploy_ck#" == '#yes#' ]]; then
			$STS_SSH cp $config_temp $dir
		elif [[ "#$deploy_ck#" == '#q#' \
				|| "#$deploy_ck#" == '#quit#' ]]; then
			echo -e "\nExiting Update Config Script at User's Request.\n"
			/bin/rm $config_temp
			exit 0
		else
			echo -e "\nOk, Leaving Deployed STS Config Script As Is...\n"
		fi
	
	else

		echo -e "No Change to Config File:\n\n\t$dir\n"

	fi

done

# Clean Up...
/bin/rm $config_temp

